#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'ceres'
VERSION = '0.0.1'

top = '.'
out = 'build'

def options(ctx):
    ctx.recurse('src')
    
def configure(ctx):
    ctx.recurse('src')
    
def build(ctx):
    ctx.recurse('src')

