" Base .vimrc -- Ryan McDougall

colorscheme slate

" Set up vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'FSwitch'
Plugin 'gtags.vim'
Plugin 'fugitive.vim'
Plugin 'OmniCppComplete'
Plugin 'rhysd/vim-clang-format'
Plugin 'vim-syntastic/syntastic'
Plugin 'mileszs/ack.vim'
call vundle#end()
" :PluginList           - list configured plugins
" :PluginInstall(!)     - install (update) plugins
" :PluginSearch(!) foo  - search (or refresh cache first) for foo
" :PluginClean(!)       - confirm (or auto-approve) removal of unused plugins

filetype plugin indent on   " autoguess by file extension
set nocompatible            " use VIM settings
set autowriteall            " write buffer to file when switching
set undofile                " persistent undo
set tabstop=2               " number of spaces in a tab
set softtabstop=2           " number of spaces in a soft tab
set shiftwidth=2            " used in shifting or C indenting
set expandtab               " insert spaces for tabs
set smarttab                " prefer shiftwidth
set cindent                 " C indenting
set cinoptions=:0,g0,N-s    " minimize switch, class, ns, indenting
set ruler                   " show the cursor
set number                  " print line numbers
set incsearch               " incremental search
set hlsearch                " highlight search matches
set wildmenu                " print menu completions
set scrolloff=5             " keep lines of context when scrolling
set matchpairs+=<:>         " match angle brackets
set guioptions-=tT          " turn off annoying toolbars
set noerrorbells            " turn off annoying bells
set vb t_vb=                " turn off annoying blinking
let mapleader=","           " comma is more convenient

" Try not to clutter source directories
if isdirectory($HOME.'/.vim/swap') == 0
  :silent !mkdir -p ~/.vim/swap >/dev/null 2>&1
endif
if isdirectory($HOME.'/.vim/undo') == 0
  :silent !mkdir -p ~/.vim/undo > /dev/null 2>&1
endif
set directory=~/.vim/swap//,.,~/tmp//,/var/tmp//
set undodir=~/.vim/undo//,.,~/tmp//,/var/tmp//

" Syntax highlighting always on
if !exists ("syntax_on")
    syntax on
endif

" Save buffer
noremap <silent> <Leader>w <Esc><C-C>:w<CR>

" Cancel highlighting
nnoremap <silent> <C-C> <C-C>:nohl<CR>

" Ergonomic Esc
noremap <C-e> <Esc>
noremap! <C-e> <Esc>

" Ergonomic centering
nnoremap <Home> zz

" Additional scrolling
nnoremap <Backspace> <PageUp>
nnoremap <Space> <PageDown>

" Window resizing
"nnoremap <C-u> :resize +10<CR>
"nnoremap <C-d> :resize -10<CR>

" Yank until eol (w/o nl)
nnoremap Y yg_

" Yank/Put to/from system clipboard
vnoremap <Leader>y "+y
nnoremap <Leader>y "+y
vnoremap <Leader>Y "+yg_
nnoremap <Leader>Y "+yg_
vnoremap <Leader>p "+p
nnoremap <Leader>p "+p

" Buffer/Window management
nnoremap <silent> <C-n> <C-W>w
nnoremap <silent> <C-p> <C-W>W
nnoremap <silent> <C-x> :bdelete!<CR>
nnoremap <Leader>e :edit 
nnoremap <Leader>b :buffer 
nnoremap <Leader>B :bnext! \| bdelete! #<CR>
nnoremap ]b :bnext<CR>
nnoremap [b :bprevious<CR>

" Quickfix window
nnoremap <Leader>q :copen<CR>
nnoremap <Leader>Q :cclose<CR>
nnoremap ]q :cnext<CR>
nnoremap [q :cprevious<CR>

" Location window
nnoremap <Leader>l :lopen<CR>
nnoremap <Leader>L :lclose<CR>
nnoremap ]l :lnext<CR>
nnoremap [l :lprevious<CR>

" Insert newline
nnoremap <C-j> O<Esc>j

" Toggle .{c|cpp}/.{h|hpp}
nnoremap <silent> <C-a> :FSHere<CR>

" Ctag searching
nnoremap <Leader>t :tjump<Space>

" Gtag searching
nnoremap <Leader>r :Gtags -r <C-R><C-W><CR>
nnoremap <Leader>R :Gtags -s <C-R><C-W><CR>
nnoremap <Leader>f :Gtags -f %<CR>
nnoremap <Leader>g :Gtags -g 

" Search+replace word under cursor
nnoremap <Leader>s :,$s/\<<C-R><C-W>\>/

" Multi-platform find
if has("unix")
    let find="find . -name "
else
    let find="dir /b /s "
endif

" Grep word under cursor
nnoremap <C-g> :Ack <C-R><C-W> %:h

" Find file with quickfix integration
nnoremap <C-f> :cgetexpr system(find."")

" Make local file with quickfix integration
" may require modeline set CXXFLAGS='...'
nnoremap <Leader>m :make %< \|cwindow<CR>

" Auto Clang Format
autocmd FileType * :ClangFormatAutoDisable
autocmd FileType C,CPP :ClangFormatAutoEnable
"let g:clang_format#command = 'clang-format-3.6'
let g:clang_format#detect_style_files = 1 " use .clang-format
let g:clang_format#auto_format = 1        " format on write
let g:clang_format#auto_format_on_insert_leave = 1
let g:clang_format#auto_formatexpr = 1    " format on gq

" Ergonomic Clang formatting
autocmd FileType C,CPP nnoremap = gq
autocmd FileType C,CPP nnoremap == gqq
autocmd FileType C,CPP vnoremap = gq

" Syntastic
"let g:syntastic_cpp_clang_tidy_exec = 'clang-tidy-3.6'
let g:syntastic_cpp_checkers = ['clang_tidy']
let g:syntastic_cpp_compiler_options = '-std=c++11'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 2 " close location-list when empty

" Google Style
autocmd FileType CPP set tabstop=2 shiftwidth=2 softtabstop=2
set cinoptions=g1,h1,N-s

" Eclipse Style
autocmd! FileType Java set tabstop=4 shiftwidth=4 softtabstop=4

" PEP 8 Style
autocmd! FileType Python set tabstop=8 shiftwidth=4 softtabstop=4

" JavaScript
autocmd! FileType JavaScript set tabstop=2 shiftwidth=2 softtabstop=2

" Generate local C++ tags file
nnoremap <silent> <Leader>G+ :!ctags -R --languages=C,C++ --c++-kinds=+p --fields=+aiS -f cpp.tags<CR>
set tags+=./cpp.tags,cpp.tags,

" Generate local C# tags file
nnoremap <silent> <Leader>G# :!ctags -R --languages=C\# --fields=+aiS -f cs.tags<CR>
set tags+=./cs.tags,cs.tags

" Generate local Java tags file
nnoremap <silent> <Leader>Gj :!ctags -R --languages=Java --fields=+aiS -f java.tags<CR>
set tags+=./java.tags,java.tags

" Generate local Python tags file
nnoremap <silent> <Leader>Gpy :!ctags -R --languages=Python --python-kinds=-i --fields=+aiS -f py.tags<CR>
set tags+=./py.tags,py.tags

" Generate local JavaScript tags file
"nnoremap <silent> <Leader>Gjs :!ctags -R --languages=JavaScript --sort=yes -f js.tags<CR>
nnoremap <silent> <Leader>Gjs :!find .
      \ -type f -name '*.js'
      \ -not -path '*/.svn/*'
      \ -not -path '*/.git/*'
      \ -not -path '*/.hg/*'
      \ -not -path '*/log/*'
      \ -not -path '*/html/*'
      \ -not -path '*/node_modules/*'
      \ -not -path '*/bazel-*'
      \ -not -path '*/build/*'
      \ -exec jsctags {} -f \; \| sed '/^$/d' \| sort > js.tags<CR>
set tags+=./js.tags,js.tags

" Generate local protobuf tags file
nnoremap <silent> <Leader>Gpb :!ctags -R --languages=protobuf --extra=+fq -f protobuf.tags<CR>
set tags+=./protobuf.tags,protobuf.tags

" Generate /usr/src C++ tags files
nnoremap <silent> <Leader>Gs :!ctags -R --languages=C,C++ --c++-kinds=+p --fields=+aiS --extra=+fq -f source.tags /usr/src<CR>
set tags+=./source.tags,source.tags

nnoremap <silent> <Leader>Gg :!find .
      \ \(
      \ -name '*.cpp' -or
      \ -name '*.cxx' -or
      \ -name '*.cc' -or
      \ -name '*.c' -or
      \ -name '*.hpp' -or
      \ -name '*.hxx' -or
      \ -name '*.hh' -or
      \ -name '*.h' -or
      \ -name '*.ipp' -or
      \ -name '*.tpp' \)
      \ -not -path '*/.svn/*'
      \ -not -path '*/.git/*'
      \ -not -path '*/.hg/*'
      \ -not -path '*/log/*'
      \ -not -path '*/html/*'
      \ -not -path '*/node_modules/*'
      \ -not -path '*/bazel-*'
      \ -not -path '*/build/*' \|
      \ env GTAGSFORCECPP=1 gtags -f-
      \<CR>

" C++ OmniCppComplete
set completeopt=menu,longest
let OmniCpp_ShowPrototypeInAbbr = 1 "show function parameters
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]
imap <C-O> <C-X><C-O>

" Avoid searching boost headers on complete
set include=^\\s*#\\s*include\ \\(<boost/\\)\\@!

" Java eclim bindings
nnoremap <Leader>ji :JavaImport<CR>
nnoremap <Leader>jd :JavaDocSearch -x declarations<CR>
nnoremap <Leader>js :JavaSearchContext<CR>
nnoremap <Leader>ja :JavaGetSet <CR>
nnoremap <Leader>jc :JavaConstructor <CR>
nnoremap <Leader>jr :JavaRename
nnoremap <Leader>jf :%JavaFormat <CR>

" Hex editing
nnoremap <Leader>h :%!xxd -g1<CR>
nnoremap <Leader>H :%!xxd -r<CR>:set bin<CR>:write<CR>:set nobin<CR>

" Text editing
nnoremap <Leader>k :setlocal spell<CR>
nnoremap <Leader>K :setlocal nospell<CR>

" Windows GUI tweaks
if has("gui_win32")
    set guifont=DejaVu_Sans_Mono:h9:cANSI
    set shellslash "unify shell path seperator handling (eg. Cygwin)
endif

" Mac GUI tweaks
if has("gui_macvim")
    " Fix redraw issues on MacOSX
    autocmd FocusGained * :redraw!
endif

" Neovim integration
if has('nvim')
    " Terminal history
    set scrollback=100000

    " Neovim terminal bindings
    nnoremap <C-\>t :set nonumber <bar> :term<CR>
    nnoremap <C-\>s :set nonumber <bar> :split +:term<CR>
    nnoremap <C-\>v :set nonumber <bar> :vsplit +:term<CR>
    tnoremap <Esc><Esc> <C-\><C-n>

    " Ergonomic versions
    nnoremap <C-\><C-t> :set nonumber <bar> :term<CR>
    nnoremap <C-\><C-s> :set nonumber <bar> :split +:term<CR>
    nnoremap <C-\><C-v> :set nonumber <bar> :vsplit +:term<CR>
    tnoremap <C-e><C-e> <C-\><C-n>

    " Fast window switching
    tnoremap <C-n> <C-\><C-n><C-w>wi
    tnoremap <C-p> <C-\><C-n><C-w>Wi

    " Always start on insert for terminal
    ":au BufEnter * if &buftype == 'terminal' | :startinsert | endif
endif
