#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_cxx')
    ctx.add_option('--build', action='store', default='', help='build configuration')

def configure(ctx):
    ctx.load('compiler_cxx')
    ctx.env.variant = ctx.options.build
    default = ctx.env

    ctx.setenv('debug', default)
    ctx.env.append_unique('CXXFLAGS', ['-g', '-std=c++11'])
    ctx.env.append_unique('DEFINES', 'DEBUG')

    ctx.setenv('release', default)
    ctx.env.append_unique('CXXFLAGS', ['-g', '-O2', '-std=c++11'])
    ctx.env.append_unique('DEFINES', 'RELEASE')

    ctx.setenv('shipping', default)
    ctx.env.append_unique('CXXFLAGS', ['-O2', '-std=c++11'])
    ctx.env.append_unique('DEFINES', 'SHIPPING')

def build(ctx):
    variant = ctx.variant if len(ctx.variant) > 0 else ctx.env.variant
    print 'Using build configuration: {0}'.format(variant.upper())

    INCLUDES = '.'
    DEFINES = ctx.env.DEFINES

    ctx.env = ctx.all_envs[variant]

    ctx.program(source='main.cpp', target='game', use='error socket',
            includes=INCLUDES, defines=DEFINES)

    # TODO: platform-specific static libraries
    ctx.objects(source='platform/posix/error.cpp', target='error', 
            includes=INCLUDES, defines=DEFINES)
    ctx.objects(source='platform/posix/socket.cpp', target='socket', 
            includes=INCLUDES, defines=DEFINES)

# Create a custom builder for each combination of context and configuration 
from waflib.Build import BuildContext, CleanContext, InstallContext, UninstallContext
for configuration in ['debug', 'release', 'shipping']:
    for context in (BuildContext, CleanContext, InstallContext, UninstallContext):
        class Builder(context):
            cmd =  configuration + '_' + context.__name__.replace('Context','').lower()
            variant = configuration
