#include "error.hpp"

namespace ctl {
const std::array<detail::condition_entry, 125> posix_domain::categories_ = {
  detail::condition_entry{},
  detail::condition_entry{"Operation not permitted"},
  detail::condition_entry{"No such file or directory"},
  detail::condition_entry{"No such process"},
  detail::condition_entry{"Interrupted system call"},
  detail::condition_entry{"I/O error"},
  detail::condition_entry{"No such device or address"},
  detail::condition_entry{"Arg list too long"},
  detail::condition_entry{"Exec format error"},
  detail::condition_entry{"Bad file number"},
  detail::condition_entry{"No child processes"},
  detail::condition_entry{"Try again"},
  detail::condition_entry{"Out of memory"},
  detail::condition_entry{"Permission denied"},
  detail::condition_entry{"Bad address"},
  detail::condition_entry{"Block device required"},
  detail::condition_entry{"Device or resource busy"},
  detail::condition_entry{"File exists"},
  detail::condition_entry{"Cross-device link"},
  detail::condition_entry{"No such device"},
  detail::condition_entry{"Not a directory"},
  detail::condition_entry{"Is a directory"},
  detail::condition_entry{"Invalid argument"},
  detail::condition_entry{"File table overflow"},
  detail::condition_entry{"Too many open files"},
  detail::condition_entry{"Not a typewriter"},
  detail::condition_entry{"Text file busy"},
  detail::condition_entry{"File too large"},
  detail::condition_entry{"No space left on device"},
  detail::condition_entry{"Illegal seek"},
  detail::condition_entry{"Read-only file system"},
  detail::condition_entry{"Too many links"},
  detail::condition_entry{"Broken pipe"},
  detail::condition_entry{"Math argument out of domain of func"},
  detail::condition_entry{"Math result not representable"},
  detail::condition_entry{"Resource deadlock would occur"},
  detail::condition_entry{"File name too long"},
  detail::condition_entry{"No record locks available"},
  detail::condition_entry{"Function not implemented"},
  detail::condition_entry{"Directory not empty"},
  detail::condition_entry{"Too many symbolic links encountered"},
  detail::condition_entry{"Try again"},
  detail::condition_entry{"No message of desired type"},
  detail::condition_entry{"Identifier removed"},
  detail::condition_entry{"Channel number out of range"},
  detail::condition_entry{"Level 2 not synchronized"},
  detail::condition_entry{"Level 3 halted"},
  detail::condition_entry{"Level 3 reset"},
  detail::condition_entry{"Link number out of range"},
  detail::condition_entry{"Protocol driver not attached"},
  detail::condition_entry{"No CSI structure available"},
  detail::condition_entry{"Level 2 halted"},
  detail::condition_entry{"Invalid exchange"},
  detail::condition_entry{"Invalid request descriptor"},
  detail::condition_entry{"Exchange full"},
  detail::condition_entry{"No anode"},
  detail::condition_entry{"Invalid request code"},
  detail::condition_entry{"Invalid slot"},
  detail::condition_entry{"Resource deadlock would occur"},
  detail::condition_entry{"Bad font file format"},
  detail::condition_entry{"Device not a stream"},
  detail::condition_entry{"No data available"},
  detail::condition_entry{"Timer expired"},
  detail::condition_entry{"Out of streams resources"},
  detail::condition_entry{"Machine is not on the network"},
  detail::condition_entry{"Package not installed"},
  detail::condition_entry{"Object is remote"},
  detail::condition_entry{"Link has been severed"},
  detail::condition_entry{"Advertise error"},
  detail::condition_entry{"Srmount error"},
  detail::condition_entry{"Communication error on send"},
  detail::condition_entry{"Protocol error"},
  detail::condition_entry{"Multihop attempted"},
  detail::condition_entry{"RFS specific error"},
  detail::condition_entry{"Not a data message"},
  detail::condition_entry{"Value too large for defined data type"},
  detail::condition_entry{"Name not unique on network"},
  detail::condition_entry{"File descriptor in bad state"},
  detail::condition_entry{"Remote address changed"},
  detail::condition_entry{"Can not access a needed shared library"},
  detail::condition_entry{"Accessing a corrupted shared library"},
  detail::condition_entry{".lib section in a.out corrupted"},
  detail::condition_entry{"Attempting to link in too many shared libraries"},
  detail::condition_entry{"Cannot exec a shared library directly"},
  detail::condition_entry{"Illegal byte sequence"},
  detail::condition_entry{"Interrupted system call should be restarted"},
  detail::condition_entry{"Streams pipe error"},
  detail::condition_entry{"Too many users"},
  detail::condition_entry{"Socket operation on non-socket"},
  detail::condition_entry{"Destination address required"},
  detail::condition_entry{"Message too long"},
  detail::condition_entry{"Protocol wrong type for socket"},
  detail::condition_entry{"Protocol not available"},
  detail::condition_entry{"Protocol not supported"},
  detail::condition_entry{"Socket type not supported"},
  detail::condition_entry{"Operation not supported on transport endpoint"},
  detail::condition_entry{"Protocol family not supported"},
  detail::condition_entry{"Address family not supported by protocol"},
  detail::condition_entry{"Address already in use"},
  detail::condition_entry{"Cannot assign requested address"},
  detail::condition_entry{"Network is down"},
  detail::condition_entry{"Network is unreachable"},
  detail::condition_entry{"Network dropped connection because of reset"},
  detail::condition_entry{"Software caused connection abort"},
  detail::condition_entry{"Connection reset by peer"},
  detail::condition_entry{"No buffer space available"},
  detail::condition_entry{"Transport endpoint is already connected"},
  detail::condition_entry{"Transport endpoint is not connected"},
  detail::condition_entry{"Cannot send after transport endpoint shutdown"},
  detail::condition_entry{"Too many references: cannot splice"},
  detail::condition_entry{"Connection timed out"},
  detail::condition_entry{"Connection refused"},
  detail::condition_entry{"Host is down"},
  detail::condition_entry{"No route to host"},
  detail::condition_entry{"Operation already in progress"},
  detail::condition_entry{"Operation now in progress"},
  detail::condition_entry{"Stale NFS file handle"},
  detail::condition_entry{"Structure needs cleaning"},
  detail::condition_entry{"Not a XENIX named type file"},
  detail::condition_entry{"No XENIX semaphores available"},
  detail::condition_entry{"Is a named type file"},
  detail::condition_entry{"Remote I/O error"},
  detail::condition_entry{"Quota exceeded"},
  detail::condition_entry{"No medium found"},
  detail::condition_entry{"Wrong medium type "},
};

const std::array<detail::condition_entry, 200> win32_domain::categories_ = {
  detail::condition_entry{"ERROR_SUCCESS"},
  detail::condition_entry{"ERROR_INVALID_FUNCTION"},
  detail::condition_entry{"ERROR_FILE_NOT_FOUND"},
  detail::condition_entry{"ERROR_PATH_NOT_FOUND"},
  detail::condition_entry{"ERROR_TOO_MANY_OPEN_FILES"},
  detail::condition_entry{"ERROR_ACCESS_DENIED"},
  detail::condition_entry{"ERROR_INVALID_HANDLE"},
  detail::condition_entry{"ERROR_ARENA_TRASHED"},
  detail::condition_entry{"ERROR_NOT_ENOUGH_MEMORY"},
  detail::condition_entry{"ERROR_INVALID_BLOCK"},
  detail::condition_entry{"ERROR_BAD_ENVIRONMENT"},
  detail::condition_entry{"ERROR_BAD_FORMAT"},
  detail::condition_entry{"ERROR_INVALID_ACCESS"},
  detail::condition_entry{"ERROR_INVALID_DATA"},
  detail::condition_entry{"ERROR_OUTOFMEMORY"},
  detail::condition_entry{"ERROR_INVALID_DRIVE"},
  detail::condition_entry{"ERROR_CURRENT_DIRECTORY"},
  detail::condition_entry{"ERROR_NOT_SAME_DEVICE"},
  detail::condition_entry{"ERROR_NO_MORE_FILES"},
  detail::condition_entry{"ERROR_WRITE_PROTECT"},
  detail::condition_entry{"ERROR_BAD_UNIT"},
  detail::condition_entry{"ERROR_NOT_READY"},
  detail::condition_entry{"ERROR_BAD_COMMAND"},
  detail::condition_entry{"ERROR_CRC"},
  detail::condition_entry{"ERROR_BAD_LENGTH"},
  detail::condition_entry{"ERROR_SEEK"},
  detail::condition_entry{"ERROR_NOT_DOS_DISK"},
  detail::condition_entry{"ERROR_SECTOR_NOT_FOUND"},
  detail::condition_entry{"ERROR_OUT_OF_PAPER"},
  detail::condition_entry{"ERROR_WRITE_FAULT"},
  detail::condition_entry{"ERROR_READ_FAULT"},
  detail::condition_entry{"ERROR_GEN_FAILURE"},
  detail::condition_entry{"ERROR_SHARING_VIOLATION"},
  detail::condition_entry{"ERROR_LOCK_VIOLATION"},
  detail::condition_entry{"ERROR_WRONG_DISK"},
  detail::condition_entry{"ERROR_SHARING_BUFFER_EXCEEDED"},
  detail::condition_entry{"ERROR_HANDLE_EOF"},
  detail::condition_entry{"ERROR_HANDLE_DISK_FULL"},
  detail::condition_entry{"ERROR_NOT_SUPPORTED"},
  detail::condition_entry{"ERROR_REM_NOT_LIST"},
  detail::condition_entry{"ERROR_DUP_NAME"},
  detail::condition_entry{"ERROR_BAD_NETPATH"},
  detail::condition_entry{"ERROR_NETWORK_BUSY"},
  detail::condition_entry{"ERROR_DEV_NOT_EXIST"},
  detail::condition_entry{"ERROR_TOO_MANY_CMDS"},
  detail::condition_entry{"ERROR_ADAP_HDW_ERR"},
  detail::condition_entry{"ERROR_BAD_NET_RESP"},
  detail::condition_entry{"ERROR_UNEXP_NET_ERR"},
  detail::condition_entry{"ERROR_BAD_REM_ADAP"},
  detail::condition_entry{"ERROR_PRINTQ_FULL"},
  detail::condition_entry{"ERROR_NO_SPOOL_SPACE"},
  detail::condition_entry{"ERROR_PRINT_CANCELED"},
  detail::condition_entry{"ERROR_NETNAME_DELETED"},
  detail::condition_entry{"ERROR_NETWORK_ACCESS_DENIED"},
  detail::condition_entry{"ERROR_BAD_DEV_TYPE"},
  detail::condition_entry{"ERROR_BAD_NET_NAME"},
  detail::condition_entry{"ERROR_TOO_MANY_NAMES"},
  detail::condition_entry{"ERROR_TOO_MANY_SESS"},
  detail::condition_entry{"ERROR_SHARING_PAUSED"},
  detail::condition_entry{"ERROR_REQ_NOT_ACCEP"},
  detail::condition_entry{"ERROR_REDIR_PAUSED"},
  detail::condition_entry{"ERROR_FILE_EXISTS"},
  detail::condition_entry{"ERROR_CANNOT_MAKE"},
  detail::condition_entry{"ERROR_FAIL_I24"},
  detail::condition_entry{"ERROR_OUT_OF_STRUCTURES"},
  detail::condition_entry{"ERROR_ALREADY_ASSIGNED"},
  detail::condition_entry{"ERROR_INVALID_PASSWORD"},
  detail::condition_entry{"ERROR_INVALID_PARAMETER"},
  detail::condition_entry{"ERROR_NET_WRITE_FAULT"},
  detail::condition_entry{"ERROR_NO_PROC_SLOTS"},
  detail::condition_entry{"ERROR_TOO_MANY_SEMAPHORES"},
  detail::condition_entry{"ERROR_EXCL_SEM_ALREADY_OWNED"},
  detail::condition_entry{"ERROR_SEM_IS_SET"},
  detail::condition_entry{"ERROR_TOO_MANY_SEM_REQUESTS"},
  detail::condition_entry{"ERROR_INVALID_AT_INTERRUPT_TIME"},
  detail::condition_entry{"ERROR_SEM_OWNER_DIED"},
  detail::condition_entry{"ERROR_SEM_USER_LIMIT"},
  detail::condition_entry{"ERROR_DISK_CHANGE"},
  detail::condition_entry{"ERROR_DRIVE_LOCKED"},
  detail::condition_entry{"ERROR_BROKEN_PIPE"},
  detail::condition_entry{"ERROR_OPEN_FAILED"},
  detail::condition_entry{"ERROR_BUFFER_OVERFLOW"},
  detail::condition_entry{"ERROR_DISK_FULL"},
  detail::condition_entry{"ERROR_NO_MORE_SEARCH_HANDLES"},
  detail::condition_entry{"ERROR_INVALID_TARGET_HANDLE"},
  detail::condition_entry{"ERROR_INVALID_CATEGORY"},
  detail::condition_entry{"ERROR_INVALID_VERIFY_SWITCH"},
  detail::condition_entry{"ERROR_BAD_DRIVER_LEVEL"},
  detail::condition_entry{"ERROR_CALL_NOT_IMPLEMENTED"},
  detail::condition_entry{"ERROR_SEM_TIMEOUT"},
  detail::condition_entry{"ERROR_INSUFFICIENT_BUFFER"},
  detail::condition_entry{"ERROR_INVALID_NAME"},
  detail::condition_entry{"ERROR_INVALID_LEVEL"},
  detail::condition_entry{"ERROR_NO_VOLUME_LABEL"},
  detail::condition_entry{"ERROR_MOD_NOT_FOUND"},
  detail::condition_entry{"ERROR_PROC_NOT_FOUND"},
  detail::condition_entry{"ERROR_WAIT_NO_CHILDREN"},
  detail::condition_entry{"ERROR_CHILD_NOT_COMPLETE"},
  detail::condition_entry{"ERROR_DIRECT_ACCESS_HANDLE"},
  detail::condition_entry{"ERROR_NEGATIVE_SEEK"},
  detail::condition_entry{"ERROR_SEEK_ON_DEVICE"},
  detail::condition_entry{"ERROR_IS_JOIN_TARGET"},
  detail::condition_entry{"ERROR_IS_JOINED"},
  detail::condition_entry{"ERROR_IS_SUBSTED"},
  detail::condition_entry{"ERROR_NOT_JOINED"},
  detail::condition_entry{"ERROR_NOT_SUBSTED"},
  detail::condition_entry{"ERROR_JOIN_TO_JOIN"},
  detail::condition_entry{"ERROR_SUBST_TO_SUBST"},
  detail::condition_entry{"ERROR_JOIN_TO_SUBST"},
  detail::condition_entry{"ERROR_SUBST_TO_JOIN"},
  detail::condition_entry{"ERROR_BUSY_DRIVE"},
  detail::condition_entry{"ERROR_SAME_DRIVE"},
  detail::condition_entry{"ERROR_DIR_NOT_ROOT"},
  detail::condition_entry{"ERROR_DIR_NOT_EMPTY"},
  detail::condition_entry{"ERROR_IS_SUBST_PATH"},
  detail::condition_entry{"ERROR_IS_JOIN_PATH"},
  detail::condition_entry{"ERROR_PATH_BUSY"},
  detail::condition_entry{"ERROR_IS_SUBST_TARGET"},
  detail::condition_entry{"ERROR_SYSTEM_TRACE"},
  detail::condition_entry{"ERROR_INVALID_EVENT_COUNT"},
  detail::condition_entry{"ERROR_TOO_MANY_MUXWAITERS"},
  detail::condition_entry{"ERROR_INVALID_LIST_FORMAT"},
  detail::condition_entry{"ERROR_LABEL_TOO_LONG"},
  detail::condition_entry{"ERROR_TOO_MANY_TCBS"},
  detail::condition_entry{"ERROR_SIGNAL_REFUSED"},
  detail::condition_entry{"ERROR_DISCARDED"},
  detail::condition_entry{"ERROR_NOT_LOCKED"},
  detail::condition_entry{"ERROR_BAD_THREADID_ADDR"},
  detail::condition_entry{"ERROR_BAD_ARGUMENTS"},
  detail::condition_entry{"ERROR_BAD_PATHNAME"},
  detail::condition_entry{"ERROR_SIGNAL_PENDING"},
  detail::condition_entry{"ERROR_MAX_THRDS_REACHED"},
  detail::condition_entry{"ERROR_LOCK_FAILED"},
  detail::condition_entry{"ERROR_BUSY"},
  detail::condition_entry{"ERROR_CANCEL_VIOLATION"},
  detail::condition_entry{"ERROR_ATOMIC_LOCKS_NOT_SUPPORTED"},
  detail::condition_entry{"ERROR_INVALID_SEGMENT_NUMBER"},
  detail::condition_entry{"ERROR_INVALID_ORDINAL"},
  detail::condition_entry{"ERROR_ALREADY_EXISTS"},
  detail::condition_entry{"ERROR_INVALID_FLAG_NUMBER"},
  detail::condition_entry{"ERROR_SEM_NOT_FOUND"},
  detail::condition_entry{"ERROR_INVALID_STARTING_CODESEG"},
  detail::condition_entry{"ERROR_INVALID_STACKSEG"},
  detail::condition_entry{"ERROR_INVALID_MODULETYPE"},
  detail::condition_entry{"ERROR_INVALID_EXE_SIGNATURE"},
  detail::condition_entry{"ERROR_EXE_MARKED_INVALID"},
  detail::condition_entry{"ERROR_BAD_EXE_FORMAT"},
  detail::condition_entry{"ERROR_ITERATED_DATA_EXCEEDS_64k"},
  detail::condition_entry{"ERROR_INVALID_MINALLOCSIZE"},
  detail::condition_entry{"ERROR_DYNLINK_FROM_INVALID_RING"},
  detail::condition_entry{"ERROR_IOPL_NOT_ENABLED"},
  detail::condition_entry{"ERROR_INVALID_SEGDPL"},
  detail::condition_entry{"ERROR_AUTODATASEG_EXCEEDS_64k"},
  detail::condition_entry{"ERROR_RING2SEG_MUST_BE_MOVABLE"},
  detail::condition_entry{"ERROR_RELOC_CHAIN_XEEDS_SEGLIM"},
  detail::condition_entry{"ERROR_INFLOOP_IN_RELOC_CHAIN"},
  detail::condition_entry{"ERROR_ENVVAR_NOT_FOUND"},
  detail::condition_entry{"ERROR_NO_SIGNAL_SENT"},
  detail::condition_entry{"ERROR_FILENAME_EXCED_RANGE"},
  detail::condition_entry{"ERROR_RING2_STACK_IN_USE"},
  detail::condition_entry{"ERROR_META_EXPANSION_TOO_LONG"},
  detail::condition_entry{"ERROR_INVALID_SIGNAL_NUMBER"},
  detail::condition_entry{"ERROR_THREAD_1_INACTIVE"},
  detail::condition_entry{"ERROR_LOCKED"},
  detail::condition_entry{"ERROR_TOO_MANY_MODULES"},
  detail::condition_entry{"ERROR_NESTING_NOT_ALLOWED"},
  detail::condition_entry{"ERROR_EXE_MACHINE_TYPE_MISMATCH"},
  detail::condition_entry{"ERROR_BAD_PIPE"},
  detail::condition_entry{"ERROR_PIPE_BUSY"},
  detail::condition_entry{"ERROR_NO_DATA"},
  detail::condition_entry{"ERROR_PIPE_NOT_CONNECTED"},
  detail::condition_entry{"ERROR_MORE_DATA"},
  detail::condition_entry{"ERROR_VC_DISCONNECTED"},
  detail::condition_entry{"ERROR_INVALID_EA_NAME"},
  detail::condition_entry{"ERROR_EA_LIST_INCONSISTENT"},
  detail::condition_entry{"WAIT_TIMEOUT"},
  detail::condition_entry{"ERROR_NO_MORE_ITEMS"},
  detail::condition_entry{"ERROR_CANNOT_COPY"},
  detail::condition_entry{"ERROR_DIRECTORY"},
  detail::condition_entry{"ERROR_EAS_DIDNT_FIT"},
  detail::condition_entry{"ERROR_EA_FILE_CORRUPT"},
  detail::condition_entry{"ERROR_EA_TABLE_FULL"},
  detail::condition_entry{"ERROR_INVALID_EA_HANDLE"},
  detail::condition_entry{"ERROR_EAS_NOT_SUPPORTED"},
  detail::condition_entry{"ERROR_NOT_OWNER"},
  detail::condition_entry{"ERROR_TOO_MANY_POSTS"},
  detail::condition_entry{"ERROR_PARTIAL_COPY"},
  detail::condition_entry{"ERROR_OPLOCK_NOT_GRANTED"},
  detail::condition_entry{"ERROR_INVALID_OPLOCK_PROTOCOL"},
  detail::condition_entry{"ERROR_MR_MID_NOT_FOUND"},
  detail::condition_entry{"ERROR_INVALID_ADDRESS"},
  detail::condition_entry{"ERROR_ARITHMETIC_OVERFLOW"},
  detail::condition_entry{"ERROR_PIPE_CONNECTED"},
  detail::condition_entry{"ERROR_PIPE_LISTENING"},
  detail::condition_entry{"ERROR_EA_ACCESS_DENIED"},
  detail::condition_entry{"ERROR_OPERATION_ABORTED"},
  detail::condition_entry{"ERROR_IO_INCOMPLETE"},
  detail::condition_entry{"ERROR_IO_PENDING"},
  detail::condition_entry{"ERROR_NOACCESS"},
  detail::condition_entry{"ERROR_SWAPERROR"},
};

std::map<uint64_t, uint64_t> const win32_domain::condition_table_ = {
  {0u, 0u},     {1u, 1u},     {2u, 2u},     {3u, 3u},     {4u, 4u},     {5u, 5u},     {6u, 6u},
  {7u, 7u},     {8u, 8u},     {9u, 9u},     {10u, 10u},   {11u, 11u},   {12u, 12u},   {13u, 13u},
  {14u, 14u},   {15u, 15u},   {16u, 16u},   {17u, 17u},   {18u, 18u},   {19u, 19u},   {20u, 20u},
  {21u, 21u},   {22u, 22u},   {23u, 23u},   {24u, 24u},   {25u, 25u},   {26u, 26u},   {27u, 27u},
  {28u, 28u},   {29u, 29u},   {30u, 30u},   {31u, 31u},   {32u, 32u},   {33u, 33u},   {34u, 34u},
  {36u, 35u},   {38u, 36u},   {39u, 37u},   {50u, 38u},   {51u, 39u},   {52u, 40u},   {53u, 41u},
  {54u, 42u},   {55u, 43u},   {56u, 44u},   {57u, 45u},   {58u, 46u},   {59u, 47u},   {60u, 48u},
  {61u, 49u},   {62u, 50u},   {63u, 51u},   {64u, 52u},   {65u, 53u},   {66u, 54u},   {67u, 55u},
  {68u, 56u},   {69u, 57u},   {70u, 58u},   {71u, 59u},   {72u, 60u},   {80u, 61u},   {82u, 62u},
  {83u, 63u},   {84u, 64u},   {85u, 65u},   {86u, 66u},   {87u, 67u},   {88u, 68u},   {89u, 69u},
  {100u, 70u},  {101u, 71u},  {102u, 72u},  {103u, 73u},  {104u, 74u},  {105u, 75u},  {106u, 76u},
  {107u, 77u},  {108u, 78u},  {109u, 79u},  {110u, 80u},  {111u, 81u},  {112u, 82u},  {113u, 83u},
  {114u, 84u},  {117u, 85u},  {118u, 86u},  {119u, 87u},  {120u, 88u},  {121u, 89u},  {122u, 90u},
  {123u, 91u},  {124u, 92u},  {125u, 93u},  {126u, 94u},  {127u, 95u},  {128u, 96u},  {129u, 97u},
  {130u, 98u},  {131u, 99u},  {132u, 100u}, {133u, 101u}, {134u, 102u}, {135u, 103u}, {136u, 104u},
  {137u, 105u}, {138u, 106u}, {139u, 107u}, {140u, 108u}, {141u, 109u}, {142u, 110u}, {143u, 111u},
  {144u, 112u}, {145u, 113u}, {146u, 114u}, {147u, 115u}, {148u, 116u}, {149u, 117u}, {150u, 118u},
  {151u, 119u}, {152u, 120u}, {153u, 121u}, {154u, 122u}, {155u, 123u}, {156u, 124u}, {157u, 125u},
  {158u, 126u}, {159u, 127u}, {160u, 128u}, {161u, 129u}, {162u, 130u}, {164u, 131u}, {167u, 132u},
  {170u, 133u}, {173u, 134u}, {174u, 135u}, {180u, 136u}, {182u, 137u}, {183u, 138u}, {186u, 139u},
  {187u, 140u}, {188u, 141u}, {189u, 142u}, {190u, 143u}, {191u, 144u}, {192u, 145u}, {193u, 146u},
  {194u, 147u}, {195u, 148u}, {196u, 149u}, {197u, 150u}, {198u, 151u}, {199u, 152u}, {200u, 153u},
  {201u, 154u}, {202u, 155u}, {203u, 156u}, {205u, 157u}, {206u, 158u}, {207u, 159u}, {208u, 160u},
  {209u, 161u}, {210u, 162u}, {212u, 163u}, {214u, 164u}, {215u, 165u}, {216u, 166u}, {230u, 167u},
  {231u, 168u}, {232u, 169u}, {233u, 170u}, {234u, 171u}, {240u, 172u}, {254u, 173u}, {255u, 174u},
  {258u, 175u}, {259u, 176u}, {266u, 177u}, {267u, 178u}, {275u, 179u}, {276u, 180u}, {277u, 181u},
  {278u, 182u}, {282u, 183u}, {288u, 184u}, {298u, 185u}, {299u, 186u}, {300u, 187u}, {301u, 188u},
  {317u, 189u}, {487u, 190u}, {534u, 191u}, {535u, 192u}, {536u, 193u}, {994u, 194u}, {995u, 195u},
  {996u, 196u}, {997u, 197u}, {998u, 198u}, {999u, 199u},
};

std::size_t stable_hash(std::string_view str) {
  static const auto shuffle_ = [](std::uint64_t block) {
    return  // clang-format off
      ((block & 0xFFFF'0000'0000'0000) >> 16) |
      ((block & 0x0000'FFFF'0000'0000) >> 32) |
      ((block & 0x0000'0000'FFFF'0000) << 32) |
      ((block & 0x0000'0000'0000'FFFF) << 16);
    // clang-format on
  };

  static const auto diffuse_ = [](std::uint64_t block, std::uint64_t a, std::uint64_t b) {
    return (block * a) ^ (~block * b);
  };

  constexpr std::uint64_t m1 = 0xC2B2AE35C2B2AE35;
  constexpr std::uint64_t m2 = 0x42F0E1EBA9EA3693;
  constexpr std::uint64_t m3 = 0xC96C5795D7870F42;
  constexpr std::uint64_t block_size = 8;

  std::size_t i = 0;
  std::uint64_t block;
  std::uint64_t result = diffuse_(str.size(), m1, m2);

  for (; i < str.size() && block_size <= str.size(); i += block_size) {
    std::memcpy(&block, str.data() + i, block_size);
    result = shuffle_(result) ^ diffuse_(block, ~m2, m3);
  }

  for (; i < str.size(); i++) {
    result = shuffle_(result) ^ diffuse_(str[i], m3, ~m1);
  }

  return diffuse_(result, m2, ~m3);
}

}  // namespace ctl
