#include "hazard.hpp"

namespace ctl {
std::size_t stable_hash(std::string_view str) {
    static const auto shuffle_ = [](std::uint64_t block) {
        return  // clang-format off
      ((block & 0xFFFF'0000'0000'0000) >> 16) |
      ((block & 0x0000'FFFF'0000'0000) >> 32) |
      ((block & 0x0000'0000'FFFF'0000) << 32) |
      ((block & 0x0000'0000'0000'FFFF) << 16);
        // clang-format on
    };

    static const auto diffuse_ = [](std::uint64_t block, std::uint64_t a, std::uint64_t b) {
        return (block * a) ^ (~block * b);
    };

    constexpr std::uint64_t m1 = 0xC2B2AE35C2B2AE35;
    constexpr std::uint64_t m2 = 0x42F0E1EBA9EA3693;
    constexpr std::uint64_t m3 = 0xC96C5795D7870F42;
    constexpr std::uint64_t block_size = 8;

    std::size_t i = 0;
    std::uint64_t block;
    std::uint64_t result = diffuse_(str.size(), m1, m2);

    for (; i < str.size() && block_size <= str.size(); i += block_size) {
        std::memcpy(&block, str.data() + i, block_size);
        result = shuffle_(result) ^ diffuse_(block, ~m2, m3);
    }

    for (; i < str.size(); i++) {
        result = shuffle_(result) ^ diffuse_(str[i], m3, ~m1);
    }

    return diffuse_(result, m2, ~m3);
}

const std::array<condition_entry, 125> posix_domain::conditions_ = {
    condition_entry{},
    condition_entry{"Operation not permitted"},
    condition_entry{"No such file or directory"},
    condition_entry{"No such process"},
    condition_entry{"Interrupted system call"},
    condition_entry{"I/O error"},
    condition_entry{"No such device or address"},
    condition_entry{"Arg list too long"},
    condition_entry{"Exec format error"},
    condition_entry{"Bad file number"},
    condition_entry{"No child processes"},
    condition_entry{"Try again"},
    condition_entry{"Out of memory"},
    condition_entry{"Permission denied"},
    condition_entry{"Bad address"},
    condition_entry{"Block device required"},
    condition_entry{"Device or resource busy"},
    condition_entry{"File exists"},
    condition_entry{"Cross-device link"},
    condition_entry{"No such device"},
    condition_entry{"Not a directory"},
    condition_entry{"Is a directory"},
    condition_entry{"Invalid argument"},
    condition_entry{"File table overflow"},
    condition_entry{"Too many open files"},
    condition_entry{"Not a typewriter"},
    condition_entry{"Text file busy"},
    condition_entry{"File too large"},
    condition_entry{"No space left on device"},
    condition_entry{"Illegal seek"},
    condition_entry{"Read-only file system"},
    condition_entry{"Too many links"},
    condition_entry{"Broken pipe"},
    condition_entry{"Math argument out of domain of func"},
    condition_entry{"Math result not representable"},
    condition_entry{"Resource deadlock would occur"},
    condition_entry{"File name too long"},
    condition_entry{"No record locks available"},
    condition_entry{"Function not implemented"},
    condition_entry{"Directory not empty"},
    condition_entry{"Too many symbolic links encountered"},
    condition_entry{"Try again"},
    condition_entry{"No message of desired type"},
    condition_entry{"Identifier removed"},
    condition_entry{"Channel number out of range"},
    condition_entry{"Level 2 not synchronized"},
    condition_entry{"Level 3 halted"},
    condition_entry{"Level 3 reset"},
    condition_entry{"Link number out of range"},
    condition_entry{"Protocol driver not attached"},
    condition_entry{"No CSI structure available"},
    condition_entry{"Level 2 halted"},
    condition_entry{"Invalid exchange"},
    condition_entry{"Invalid request descriptor"},
    condition_entry{"Exchange full"},
    condition_entry{"No anode"},
    condition_entry{"Invalid request code"},
    condition_entry{"Invalid slot"},
    condition_entry{"Resource deadlock would occur"},
    condition_entry{"Bad font file format"},
    condition_entry{"Device not a stream"},
    condition_entry{"No data available"},
    condition_entry{"Timer expired"},
    condition_entry{"Out of streams resources"},
    condition_entry{"Machine is not on the network"},
    condition_entry{"Package not installed"},
    condition_entry{"Object is remote"},
    condition_entry{"Link has been severed"},
    condition_entry{"Advertise error"},
    condition_entry{"Srmount error"},
    condition_entry{"Communication error on send"},
    condition_entry{"Protocol error"},
    condition_entry{"Multihop attempted"},
    condition_entry{"RFS specific error"},
    condition_entry{"Not a data message"},
    condition_entry{"Value too large for defined data type"},
    condition_entry{"Name not unique on network"},
    condition_entry{"File descriptor in bad state"},
    condition_entry{"Remote address changed"},
    condition_entry{"Can not access a needed shared library"},
    condition_entry{"Accessing a corrupted shared library"},
    condition_entry{".lib section in a.out corrupted"},
    condition_entry{"Attempting to link in too many shared libraries"},
    condition_entry{"Cannot exec a shared library directly"},
    condition_entry{"Illegal byte sequence"},
    condition_entry{"Interrupted system call should be restarted"},
    condition_entry{"Streams pipe error"},
    condition_entry{"Too many users"},
    condition_entry{"Socket operation on non-socket"},
    condition_entry{"Destination address required"},
    condition_entry{"Message too long"},
    condition_entry{"Protocol wrong type for socket"},
    condition_entry{"Protocol not available"},
    condition_entry{"Protocol not supported"},
    condition_entry{"Socket type not supported"},
    condition_entry{"Operation not supported on transport endpoint"},
    condition_entry{"Protocol family not supported"},
    condition_entry{"Address family not supported by protocol"},
    condition_entry{"Address already in use"},
    condition_entry{"Cannot assign requested address"},
    condition_entry{"Network is down"},
    condition_entry{"Network is unreachable"},
    condition_entry{"Network dropped connection because of reset"},
    condition_entry{"Software caused connection abort"},
    condition_entry{"Connection reset by peer"},
    condition_entry{"No buffer space available"},
    condition_entry{"Transport endpoint is already connected"},
    condition_entry{"Transport endpoint is not connected"},
    condition_entry{"Cannot send after transport endpoint shutdown"},
    condition_entry{"Too many references: cannot splice"},
    condition_entry{"Connection timed out"},
    condition_entry{"Connection refused"},
    condition_entry{"Host is down"},
    condition_entry{"No route to host"},
    condition_entry{"Operation already in progress"},
    condition_entry{"Operation now in progress"},
    condition_entry{"Stale NFS file handle"},
    condition_entry{"Structure needs cleaning"},
    condition_entry{"Not a XENIX named type file"},
    condition_entry{"No XENIX semaphores available"},
    condition_entry{"Is a named type file"},
    condition_entry{"Remote I/O error"},
    condition_entry{"Quota exceeded"},
    condition_entry{"No medium found"},
    condition_entry{"Wrong medium type "},
};

const std::array<detail::condition_entry, 199> win32_system::conditions_ = {
    {condition_entry{"ERROR_SUCCESS"}},
    {condition_entry{"ERROR_INVALID_FUNCTION"}},
    {condition_entry{"ERROR_FILE_NOT_FOUND"}},
    {condition_entry{"ERROR_PATH_NOT_FOUND"}},
    {condition_entry{"ERROR_TOO_MANY_OPEN_FILES"}},
    {condition_entry{"ERROR_ACCESS_DENIED"}},
    {condition_entry{"ERROR_INVALID_HANDLE"}},
    {condition_entry{"ERROR_ARENA_TRASHED"}},
    {condition_entry{"ERROR_NOT_ENOUGH_MEMORY"}},
    {condition_entry{"ERROR_INVALID_BLOCK"}},
    {condition_entry{"ERROR_BAD_ENVIRONMENT"}},
    {condition_entry{"ERROR_BAD_FORMAT"}},
    {condition_entry{"ERROR_INVALID_ACCESS"}},
    {condition_entry{"ERROR_INVALID_DATA"}},
    {condition_entry{"ERROR_OUTOFMEMORY"}},
    {condition_entry{"ERROR_INVALID_DRIVE"}},
    {condition_entry{"ERROR_CURRENT_DIRECTORY"}},
    {condition_entry{"ERROR_NOT_SAME_DEVICE"}},
    {condition_entry{"ERROR_NO_MORE_FILES"}},
    {condition_entry{"ERROR_WRITE_PROTECT"}},
    {condition_entry{"ERROR_BAD_UNIT"}},
    {condition_entry{"ERROR_NOT_READY"}},
    {condition_entry{"ERROR_BAD_COMMAND"}},
    {condition_entry{"ERROR_CRC"}},
    {condition_entry{"ERROR_BAD_LENGTH"}},
    {condition_entry{"ERROR_SEEK"}},
    {condition_entry{"ERROR_NOT_DOS_DISK"}},
    {condition_entry{"ERROR_SECTOR_NOT_FOUND"}},
    {condition_entry{"ERROR_OUT_OF_PAPER"}},
    {condition_entry{"ERROR_WRITE_FAULT"}},
    {condition_entry{"ERROR_READ_FAULT"}},
    {condition_entry{"ERROR_GEN_FAILURE"}},
    {condition_entry{"ERROR_SHARING_VIOLATION"}},
    {condition_entry{"ERROR_LOCK_VIOLATION"}},
    {condition_entry{"ERROR_WRONG_DISK"}},
    {condition_entry{"ERROR_SHARING_BUFFER_EXCEEDED"}},
    {condition_entry{"ERROR_HANDLE_EOF"}},
    {condition_entry{"ERROR_HANDLE_DISK_FULL"}},
    {condition_entry{"ERROR_NOT_SUPPORTED"}},
    {condition_entry{"ERROR_REM_NOT_LIST"}},
    {condition_entry{"ERROR_DUP_NAME"}},
    {condition_entry{"ERROR_BAD_NETPATH"}},
    {condition_entry{"ERROR_NETWORK_BUSY"}},
    {condition_entry{"ERROR_DEV_NOT_EXIST"}},
    {condition_entry{"ERROR_TOO_MANY_CMDS"}},
    {condition_entry{"ERROR_ADAP_HDW_ERR"}},
    {condition_entry{"ERROR_BAD_NET_RESP"}},
    {condition_entry{"ERROR_UNEXP_NET_ERR"}},
    {condition_entry{"ERROR_BAD_REM_ADAP"}},
    {condition_entry{"ERROR_PRINTQ_FULL"}},
    {condition_entry{"ERROR_NO_SPOOL_SPACE"}},
    {condition_entry{"ERROR_PRINT_CANCELED"}},
    {condition_entry{"ERROR_NETNAME_DELETED"}},
    {condition_entry{"ERROR_NETWORK_ACCESS_DENIED"}},
    {condition_entry{"ERROR_BAD_DEV_TYPE"}},
    {condition_entry{"ERROR_BAD_NET_NAME"}},
    {condition_entry{"ERROR_TOO_MANY_NAMES"}},
    {condition_entry{"ERROR_TOO_MANY_SESS"}},
    {condition_entry{"ERROR_SHARING_PAUSED"}},
    {condition_entry{"ERROR_REQ_NOT_ACCEP"}},
    {condition_entry{"ERROR_REDIR_PAUSED"}},
    {condition_entry{"ERROR_FILE_EXISTS"}},
    {condition_entry{"ERROR_CANNOT_MAKE"}},
    {condition_entry{"ERROR_FAIL_I24"}},
    {condition_entry{"ERROR_OUT_OF_STRUCTURES"}},
    {condition_entry{"ERROR_ALREADY_ASSIGNED"}},
    {condition_entry{"ERROR_INVALID_PASSWORD"}},
    {condition_entry{"ERROR_INVALID_PARAMETER"}},
    {condition_entry{"ERROR_NET_WRITE_FAULT"}},
    {condition_entry{"ERROR_NO_PROC_SLOTS"}},
    {condition_entry{"ERROR_TOO_MANY_SEMAPHORES"}},
    {condition_entry{"ERROR_EXCL_SEM_ALREADY_OWNED"}},
    {condition_entry{"ERROR_SEM_IS_SET"}},
    {condition_entry{"ERROR_TOO_MANY_SEM_REQUESTS"}},
    {condition_entry{"ERROR_INVALID_AT_INTERRUPT_TIME"}},
    {condition_entry{"ERROR_SEM_OWNER_DIED"}},
    {condition_entry{"ERROR_SEM_USER_LIMIT"}},
    {condition_entry{"ERROR_DISK_CHANGE"}},
    {condition_entry{"ERROR_DRIVE_LOCKED"}},
    {condition_entry{"ERROR_BROKEN_PIPE"}},
    {condition_entry{"ERROR_OPEN_FAILED"}},
    {condition_entry{"ERROR_BUFFER_OVERFLOW"}},
    {condition_entry{"ERROR_DISK_FULL"}},
    {condition_entry{"ERROR_NO_MORE_SEARCH_HANDLES"}},
    {condition_entry{"ERROR_INVALID_TARGET_HANDLE"}},
    {condition_entry{"ERROR_INVALID_CATEGORY"}},
    {condition_entry{"ERROR_INVALID_VERIFY_SWITCH"}},
    {condition_entry{"ERROR_BAD_DRIVER_LEVEL"}},
    {condition_entry{"ERROR_CALL_NOT_IMPLEMENTED"}},
    {condition_entry{"ERROR_SEM_TIMEOUT"}},
    {condition_entry{"ERROR_INSUFFICIENT_BUFFER"}},
    {condition_entry{"ERROR_INVALID_NAME"}},
    {condition_entry{"ERROR_INVALID_LEVEL"}},
    {condition_entry{"ERROR_NO_VOLUME_LABEL"}},
    {condition_entry{"ERROR_MOD_NOT_FOUND"}},
    {condition_entry{"ERROR_PROC_NOT_FOUND"}},
    {condition_entry{"ERROR_WAIT_NO_CHILDREN"}},
    {condition_entry{"ERROR_CHILD_NOT_COMPLETE"}},
    {condition_entry{"ERROR_DIRECT_ACCESS_HANDLE"}},
    {condition_entry{"ERROR_NEGATIVE_SEEK"}},
    {condition_entry{"ERROR_SEEK_ON_DEVICE"}},
    {condition_entry{"ERROR_IS_JOIN_TARGET"}},
    {condition_entry{"ERROR_IS_JOINED"}},
    {condition_entry{"ERROR_IS_SUBSTED"}},
    {condition_entry{"ERROR_NOT_JOINED"}},
    {condition_entry{"ERROR_NOT_SUBSTED"}},
    {condition_entry{"ERROR_JOIN_TO_JOIN"}},
    {condition_entry{"ERROR_SUBST_TO_SUBST"}},
    {condition_entry{"ERROR_JOIN_TO_SUBST"}},
    {condition_entry{"ERROR_SUBST_TO_JOIN"}},
    {condition_entry{"ERROR_BUSY_DRIVE"}},
    {condition_entry{"ERROR_SAME_DRIVE"}},
    {condition_entry{"ERROR_DIR_NOT_ROOT"}},
    {condition_entry{"ERROR_DIR_NOT_EMPTY"}},
    {condition_entry{"ERROR_IS_SUBST_PATH"}},
    {condition_entry{"ERROR_IS_JOIN_PATH"}},
    {condition_entry{"ERROR_PATH_BUSY"}},
    {condition_entry{"ERROR_IS_SUBST_TARGET"}},
    {condition_entry{"ERROR_SYSTEM_TRACE"}},
    {condition_entry{"ERROR_INVALID_EVENT_COUNT"}},
    {condition_entry{"ERROR_TOO_MANY_MUXWAITERS"}},
    {condition_entry{"ERROR_INVALID_LIST_FORMAT"}},
    {condition_entry{"ERROR_LABEL_TOO_LONG"}},
    {condition_entry{"ERROR_TOO_MANY_TCBS"}},
    {condition_entry{"ERROR_SIGNAL_REFUSED"}},
    {condition_entry{"ERROR_DISCARDED"}},
    {condition_entry{"ERROR_NOT_LOCKED"}},
    {condition_entry{"ERROR_BAD_THREADID_ADDR"}},
    {condition_entry{"ERROR_BAD_ARGUMENTS"}},
    {condition_entry{"ERROR_BAD_PATHNAME"}},
    {condition_entry{"ERROR_SIGNAL_PENDING"}},
    {condition_entry{"ERROR_MAX_THRDS_REACHED"}},
    {condition_entry{"ERROR_LOCK_FAILED"}},
    {condition_entry{"ERROR_BUSY"}},
    {condition_entry{"ERROR_CANCEL_VIOLATION"}},
    {condition_entry{"ERROR_ATOMIC_LOCKS_NOT_SUPPORTED"}},
    {condition_entry{"ERROR_INVALID_SEGMENT_NUMBER"}},
    {condition_entry{"ERROR_INVALID_ORDINAL"}},
    {condition_entry{"ERROR_ALREADY_EXISTS"}},
    {condition_entry{"ERROR_INVALID_FLAG_NUMBER"}},
    {condition_entry{"ERROR_SEM_NOT_FOUND"}},
    {condition_entry{"ERROR_INVALID_STARTING_CODESEG"}},
    {condition_entry{"ERROR_INVALID_STACKSEG"}},
    {condition_entry{"ERROR_INVALID_MODULETYPE"}},
    {condition_entry{"ERROR_INVALID_EXE_SIGNATURE"}},
    {condition_entry{"ERROR_EXE_MARKED_INVALID"}},
    {condition_entry{"ERROR_BAD_EXE_FORMAT"}},
    {condition_entry{"ERROR_ITERATED_DATA_EXCEEDS_64k"}},
    {condition_entry{"ERROR_INVALID_MINALLOCSIZE"}},
    {condition_entry{"ERROR_DYNLINK_FROM_INVALID_RING"}},
    {condition_entry{"ERROR_IOPL_NOT_ENABLED"}},
    {condition_entry{"ERROR_INVALID_SEGDPL"}},
    {condition_entry{"ERROR_AUTODATASEG_EXCEEDS_64k"}},
    {condition_entry{"ERROR_RING2SEG_MUST_BE_MOVABLE"}},
    {condition_entry{"ERROR_RELOC_CHAIN_XEEDS_SEGLIM"}},
    {condition_entry{"ERROR_INFLOOP_IN_RELOC_CHAIN"}},
    {condition_entry{"ERROR_ENVVAR_NOT_FOUND"}},
    {condition_entry{"ERROR_NO_SIGNAL_SENT"}},
    {condition_entry{"ERROR_FILENAME_EXCED_RANGE"}},
    {condition_entry{"ERROR_RING2_STACK_IN_USE"}},
    {condition_entry{"ERROR_META_EXPANSION_TOO_LONG"}},
    {condition_entry{"ERROR_INVALID_SIGNAL_NUMBER"}},
    {condition_entry{"ERROR_THREAD_1_INACTIVE"}},
    {condition_entry{"ERROR_LOCKED"}},
    {condition_entry{"ERROR_TOO_MANY_MODULES"}},
    {condition_entry{"ERROR_NESTING_NOT_ALLOWED"}},
    {condition_entry{"ERROR_EXE_MACHINE_TYPE_MISMATCH"}},
    {condition_entry{"ERROR_BAD_PIPE"}},
    {condition_entry{"ERROR_PIPE_BUSY"}},
    {condition_entry{"ERROR_NO_DATA"}},
    {condition_entry{"ERROR_PIPE_NOT_CONNECTED"}},
    {condition_entry{"ERROR_MORE_DATA"}},
    {condition_entry{"ERROR_VC_DISCONNECTED"}},
    {condition_entry{"ERROR_INVALID_EA_NAME"}},
    {condition_entry{"ERROR_EA_LIST_INCONSISTENT"}},
    {condition_entry{"WAIT_TIMEOUT"}},
    {condition_entry{"ERROR_NO_MORE_ITEMS"}},
    {condition_entry{"ERROR_CANNOT_COPY"}},
    {condition_entry{"ERROR_DIRECTORY"}},
    {condition_entry{"ERROR_EAS_DIDNT_FIT"}},
    {condition_entry{"ERROR_EA_FILE_CORRUPT"}},
    {condition_entry{"ERROR_EA_TABLE_FULL"}},
    {condition_entry{"ERROR_INVALID_EA_HANDLE"}},
    {condition_entry{"ERROR_EAS_NOT_SUPPORTED"}},
    {condition_entry{"ERROR_NOT_OWNER"}},
    {condition_entry{"ERROR_TOO_MANY_POSTS"}},
    {condition_entry{"ERROR_PARTIAL_COPY"}},
    {condition_entry{"ERROR_OPLOCK_NOT_GRANTED"}},
    {condition_entry{"ERROR_INVALID_OPLOCK_PROTOCOL"}},
    {condition_entry{"ERROR_MR_MID_NOT_FOUND"}},
    {condition_entry{"ERROR_INVALID_ADDRESS"}},
    {condition_entry{"ERROR_ARITHMETIC_OVERFLOW"}},
    {condition_entry{"ERROR_PIPE_CONNECTED"}},
    {condition_entry{"ERROR_PIPE_LISTENING"}},
    {condition_entry{"ERROR_EA_ACCESS_DENIED"}},
    {condition_entry{"ERROR_OPERATION_ABORTED"}},
    {condition_entry{"ERROR_IO_INCOMPLETE"}},
    {condition_entry{"ERROR_IO_PENDING"}},
    {condition_entry{"ERROR_NOACCESS"}},
    {condition_entry{"ERROR_SWAPERROR"}},
};

std::map<uint64_t, uint64_t> const win32_system::condition_table_ = {
    {0u, 0u},     {1u, 1u},     {2u, 2u},     {3u, 3u},     {4u, 4u},     {5u, 5u},
    {6u, 6u},     {7u, 7u},     {8u, 8u},     {9u, 9u},     {10u, 10u},   {11u, 11u},
    {12u, 12u},   {13u, 13u},   {14u, 14u},   {15u, 15u},   {16u, 16u},   {17u, 17u},
    {18u, 18u},   {19u, 19u},   {20u, 20u},   {21u, 21u},   {22u, 22u},   {23u, 23u},
    {24u, 24u},   {25u, 25u},   {26u, 26u},   {27u, 27u},   {28u, 28u},   {29u, 29u},
    {30u, 30u},   {31u, 31u},   {32u, 32u},   {33u, 33u},   {34u, 34u},   {36u, 35u},
    {38u, 36u},   {39u, 37u},   {50u, 38u},   {51u, 39u},   {52u, 40u},   {53u, 41u},
    {54u, 42u},   {55u, 43u},   {56u, 44u},   {57u, 45u},   {58u, 46u},   {59u, 47u},
    {60u, 48u},   {61u, 49u},   {62u, 50u},   {63u, 51u},   {64u, 52u},   {65u, 53u},
    {66u, 54u},   {67u, 55u},   {68u, 56u},   {69u, 57u},   {70u, 58u},   {71u, 59u},
    {72u, 60u},   {80u, 61u},   {82u, 62u},   {83u, 63u},   {84u, 64u},   {85u, 65u},
    {86u, 66u},   {87u, 67u},   {88u, 68u},   {89u, 69u},   {100u, 70u},  {101u, 71u},
    {102u, 72u},  {103u, 73u},  {104u, 74u},  {105u, 75u},  {106u, 76u},  {107u, 77u},
    {108u, 78u},  {109u, 79u},  {110u, 80u},  {111u, 81u},  {112u, 82u},  {113u, 83u},
    {114u, 84u},  {117u, 85u},  {118u, 86u},  {119u, 87u},  {120u, 88u},  {121u, 89u},
    {122u, 90u},  {123u, 91u},  {124u, 92u},  {125u, 93u},  {126u, 94u},  {127u, 95u},
    {128u, 96u},  {129u, 97u},  {130u, 98u},  {131u, 99u},  {132u, 100u}, {133u, 101u},
    {134u, 102u}, {135u, 103u}, {136u, 104u}, {137u, 105u}, {138u, 106u}, {139u, 107u},
    {140u, 108u}, {141u, 109u}, {142u, 110u}, {143u, 111u}, {144u, 112u}, {145u, 113u},
    {146u, 114u}, {147u, 115u}, {148u, 116u}, {149u, 117u}, {150u, 118u}, {151u, 119u},
    {152u, 120u}, {153u, 121u}, {154u, 122u}, {155u, 123u}, {156u, 124u}, {157u, 125u},
    {158u, 126u}, {159u, 127u}, {160u, 128u}, {161u, 129u}, {162u, 130u}, {164u, 131u},
    {167u, 132u}, {170u, 133u}, {173u, 134u}, {174u, 135u}, {180u, 136u}, {182u, 137u},
    {183u, 138u}, {186u, 139u}, {187u, 140u}, {188u, 141u}, {189u, 142u}, {190u, 143u},
    {191u, 144u}, {192u, 145u}, {193u, 146u}, {194u, 147u}, {195u, 148u}, {196u, 149u},
    {197u, 150u}, {198u, 151u}, {199u, 152u}, {200u, 153u}, {201u, 154u}, {202u, 155u},
    {203u, 156u}, {205u, 157u}, {206u, 158u}, {207u, 159u}, {208u, 160u}, {209u, 161u},
    {210u, 162u}, {212u, 163u}, {214u, 164u}, {215u, 165u}, {216u, 166u}, {230u, 167u},
    {231u, 168u}, {232u, 169u}, {233u, 170u}, {234u, 171u}, {240u, 172u}, {254u, 173u},
    {255u, 174u}, {258u, 175u}, {259u, 176u}, {266u, 177u}, {267u, 178u}, {275u, 179u},
    {276u, 180u}, {277u, 181u}, {278u, 182u}, {282u, 183u}, {288u, 184u}, {298u, 185u},
    {299u, 186u}, {300u, 187u}, {301u, 188u}, {317u, 189u}, {487u, 190u}, {534u, 191u},
    {535u, 192u}, {536u, 193u}, {994u, 194u}, {995u, 195u}, {996u, 196u}, {997u, 197u},
    {998u, 198u}, {999u, 199u},
};

}  // namespace ctl
