#include "hazard.hpp"

namespace ctl {
std::size_t stable_hash(std::string_view str) {
    static const auto shuffle_ = [](std::uint64_t block) {
        return  // clang-format off
      ((block & 0xFFFF'0000'0000'0000) >> 16) |
      ((block & 0x0000'FFFF'0000'0000) >> 32) |
      ((block & 0x0000'0000'FFFF'0000) << 32) |
      ((block & 0x0000'0000'0000'FFFF) << 16);
        // clang-format on
    };

    static const auto diffuse_ = [](std::uint64_t block, std::uint64_t a, std::uint64_t b) {
        return (block * a) ^ (~block * b);
    };

    constexpr std::uint64_t m1 = 0xC2B2AE35C2B2AE35;
    constexpr std::uint64_t m2 = 0x42F0E1EBA9EA3693;
    constexpr std::uint64_t m3 = 0xC96C5795D7870F42;
    constexpr std::uint64_t block_size = 8;

    std::size_t i = 0;
    std::uint64_t block;
    std::uint64_t result = diffuse_(str.size(), m1, m2);

    for (; i < str.size() && block_size <= str.size(); i += block_size) {
        std::memcpy(&block, str.data() + i, block_size);
        result = shuffle_(result) ^ diffuse_(block, ~m2, m3);
    }

    for (; i < str.size(); i++) {
        result = shuffle_(result) ^ diffuse_(str[i], m3, ~m1);
    }

    return diffuse_(result, m2, ~m3);
}

uint64_t domain::domain_bits() const noexcept {
    return code_.domain_bits();
}

uint64_t domain::incident_bits(hazard hazard) const noexcept {
    return hazard.code_.incident_bits();
}

hazard domain::make_hazard(detail::code code) const noexcept {
    return hazard{this, code};
}

const std::array<detail::category_entry, 125> posix_domain::categories_ = {
    detail::category_entry{},
    detail::category_entry{"Operation not permitted"},
    detail::category_entry{"No such file or directory"},
    detail::category_entry{"No such process"},
    detail::category_entry{"Interrupted system call"},
    detail::category_entry{"I/O error"},
    detail::category_entry{"No such device or address"},
    detail::category_entry{"Arg list too long"},
    detail::category_entry{"Exec format error"},
    detail::category_entry{"Bad file number"},
    detail::category_entry{"No child processes"},
    detail::category_entry{"Try again"},
    detail::category_entry{"Out of memory"},
    detail::category_entry{"Permission denied"},
    detail::category_entry{"Bad address"},
    detail::category_entry{"Block device required"},
    detail::category_entry{"Device or resource busy"},
    detail::category_entry{"File exists"},
    detail::category_entry{"Cross-device link"},
    detail::category_entry{"No such device"},
    detail::category_entry{"Not a directory"},
    detail::category_entry{"Is a directory"},
    detail::category_entry{"Invalid argument"},
    detail::category_entry{"File table overflow"},
    detail::category_entry{"Too many open files"},
    detail::category_entry{"Not a typewriter"},
    detail::category_entry{"Text file busy"},
    detail::category_entry{"File too large"},
    detail::category_entry{"No space left on device"},
    detail::category_entry{"Illegal seek"},
    detail::category_entry{"Read-only file system"},
    detail::category_entry{"Too many links"},
    detail::category_entry{"Broken pipe"},
    detail::category_entry{"Math argument out of domain of func"},
    detail::category_entry{"Math result not representable"},
    detail::category_entry{"Resource deadlock would occur"},
    detail::category_entry{"File name too long"},
    detail::category_entry{"No record locks available"},
    detail::category_entry{"Function not implemented"},
    detail::category_entry{"Directory not empty"},
    detail::category_entry{"Too many symbolic links encountered"},
    detail::category_entry{"Try again"},
    detail::category_entry{"No message of desired type"},
    detail::category_entry{"Identifier removed"},
    detail::category_entry{"Channel number out of range"},
    detail::category_entry{"Level 2 not synchronized"},
    detail::category_entry{"Level 3 halted"},
    detail::category_entry{"Level 3 reset"},
    detail::category_entry{"Link number out of range"},
    detail::category_entry{"Protocol driver not attached"},
    detail::category_entry{"No CSI structure available"},
    detail::category_entry{"Level 2 halted"},
    detail::category_entry{"Invalid exchange"},
    detail::category_entry{"Invalid request descriptor"},
    detail::category_entry{"Exchange full"},
    detail::category_entry{"No anode"},
    detail::category_entry{"Invalid request code"},
    detail::category_entry{"Invalid slot"},
    detail::category_entry{"Resource deadlock would occur"},
    detail::category_entry{"Bad font file format"},
    detail::category_entry{"Device not a stream"},
    detail::category_entry{"No data available"},
    detail::category_entry{"Timer expired"},
    detail::category_entry{"Out of streams resources"},
    detail::category_entry{"Machine is not on the network"},
    detail::category_entry{"Package not installed"},
    detail::category_entry{"Object is remote"},
    detail::category_entry{"Link has been severed"},
    detail::category_entry{"Advertise error"},
    detail::category_entry{"Srmount error"},
    detail::category_entry{"Communication error on send"},
    detail::category_entry{"Protocol error"},
    detail::category_entry{"Multihop attempted"},
    detail::category_entry{"RFS specific error"},
    detail::category_entry{"Not a data message"},
    detail::category_entry{"Value too large for defined data type"},
    detail::category_entry{"Name not unique on network"},
    detail::category_entry{"File descriptor in bad state"},
    detail::category_entry{"Remote address changed"},
    detail::category_entry{"Can not access a needed shared library"},
    detail::category_entry{"Accessing a corrupted shared library"},
    detail::category_entry{".lib section in a.out corrupted"},
    detail::category_entry{"Attempting to link in too many shared libraries"},
    detail::category_entry{"Cannot exec a shared library directly"},
    detail::category_entry{"Illegal byte sequence"},
    detail::category_entry{"Interrupted system call should be restarted"},
    detail::category_entry{"Streams pipe error"},
    detail::category_entry{"Too many users"},
    detail::category_entry{"Socket operation on non-socket"},
    detail::category_entry{"Destination address required"},
    detail::category_entry{"Message too long"},
    detail::category_entry{"Protocol wrong type for socket"},
    detail::category_entry{"Protocol not available"},
    detail::category_entry{"Protocol not supported"},
    detail::category_entry{"Socket type not supported"},
    detail::category_entry{"Operation not supported on transport endpoint"},
    detail::category_entry{"Protocol family not supported"},
    detail::category_entry{"Address family not supported by protocol"},
    detail::category_entry{"Address already in use"},
    detail::category_entry{"Cannot assign requested address"},
    detail::category_entry{"Network is down"},
    detail::category_entry{"Network is unreachable"},
    detail::category_entry{"Network dropped connection because of reset"},
    detail::category_entry{"Software caused connection abort"},
    detail::category_entry{"Connection reset by peer"},
    detail::category_entry{"No buffer space available"},
    detail::category_entry{"Transport endpoint is already connected"},
    detail::category_entry{"Transport endpoint is not connected"},
    detail::category_entry{"Cannot send after transport endpoint shutdown"},
    detail::category_entry{"Too many references: cannot splice"},
    detail::category_entry{"Connection timed out"},
    detail::category_entry{"Connection refused"},
    detail::category_entry{"Host is down"},
    detail::category_entry{"No route to host"},
    detail::category_entry{"Operation already in progress"},
    detail::category_entry{"Operation now in progress"},
    detail::category_entry{"Stale NFS file handle"},
    detail::category_entry{"Structure needs cleaning"},
    detail::category_entry{"Not a XENIX named type file"},
    detail::category_entry{"No XENIX semaphores available"},
    detail::category_entry{"Is a named type file"},
    detail::category_entry{"Remote I/O error"},
    detail::category_entry{"Quota exceeded"},
    detail::category_entry{"No medium found"},
    detail::category_entry{"Wrong medium type "},
};

const std::array<detail::category_entry, 200> win32_domain::categories_ = {
    detail::category_entry{"ERROR_SUCCESS"},
    detail::category_entry{"ERROR_INVALID_FUNCTION"},
    detail::category_entry{"ERROR_FILE_NOT_FOUND"},
    detail::category_entry{"ERROR_PATH_NOT_FOUND"},
    detail::category_entry{"ERROR_TOO_MANY_OPEN_FILES"},
    detail::category_entry{"ERROR_ACCESS_DENIED"},
    detail::category_entry{"ERROR_INVALID_HANDLE"},
    detail::category_entry{"ERROR_ARENA_TRASHED"},
    detail::category_entry{"ERROR_NOT_ENOUGH_MEMORY"},
    detail::category_entry{"ERROR_INVALID_BLOCK"},
    detail::category_entry{"ERROR_BAD_ENVIRONMENT"},
    detail::category_entry{"ERROR_BAD_FORMAT"},
    detail::category_entry{"ERROR_INVALID_ACCESS"},
    detail::category_entry{"ERROR_INVALID_DATA"},
    detail::category_entry{"ERROR_OUTOFMEMORY"},
    detail::category_entry{"ERROR_INVALID_DRIVE"},
    detail::category_entry{"ERROR_CURRENT_DIRECTORY"},
    detail::category_entry{"ERROR_NOT_SAME_DEVICE"},
    detail::category_entry{"ERROR_NO_MORE_FILES"},
    detail::category_entry{"ERROR_WRITE_PROTECT"},
    detail::category_entry{"ERROR_BAD_UNIT"},
    detail::category_entry{"ERROR_NOT_READY"},
    detail::category_entry{"ERROR_BAD_COMMAND"},
    detail::category_entry{"ERROR_CRC"},
    detail::category_entry{"ERROR_BAD_LENGTH"},
    detail::category_entry{"ERROR_SEEK"},
    detail::category_entry{"ERROR_NOT_DOS_DISK"},
    detail::category_entry{"ERROR_SECTOR_NOT_FOUND"},
    detail::category_entry{"ERROR_OUT_OF_PAPER"},
    detail::category_entry{"ERROR_WRITE_FAULT"},
    detail::category_entry{"ERROR_READ_FAULT"},
    detail::category_entry{"ERROR_GEN_FAILURE"},
    detail::category_entry{"ERROR_SHARING_VIOLATION"},
    detail::category_entry{"ERROR_LOCK_VIOLATION"},
    detail::category_entry{"ERROR_WRONG_DISK"},
    detail::category_entry{"ERROR_SHARING_BUFFER_EXCEEDED"},
    detail::category_entry{"ERROR_HANDLE_EOF"},
    detail::category_entry{"ERROR_HANDLE_DISK_FULL"},
    detail::category_entry{"ERROR_NOT_SUPPORTED"},
    detail::category_entry{"ERROR_REM_NOT_LIST"},
    detail::category_entry{"ERROR_DUP_NAME"},
    detail::category_entry{"ERROR_BAD_NETPATH"},
    detail::category_entry{"ERROR_NETWORK_BUSY"},
    detail::category_entry{"ERROR_DEV_NOT_EXIST"},
    detail::category_entry{"ERROR_TOO_MANY_CMDS"},
    detail::category_entry{"ERROR_ADAP_HDW_ERR"},
    detail::category_entry{"ERROR_BAD_NET_RESP"},
    detail::category_entry{"ERROR_UNEXP_NET_ERR"},
    detail::category_entry{"ERROR_BAD_REM_ADAP"},
    detail::category_entry{"ERROR_PRINTQ_FULL"},
    detail::category_entry{"ERROR_NO_SPOOL_SPACE"},
    detail::category_entry{"ERROR_PRINT_CANCELED"},
    detail::category_entry{"ERROR_NETNAME_DELETED"},
    detail::category_entry{"ERROR_NETWORK_ACCESS_DENIED"},
    detail::category_entry{"ERROR_BAD_DEV_TYPE"},
    detail::category_entry{"ERROR_BAD_NET_NAME"},
    detail::category_entry{"ERROR_TOO_MANY_NAMES"},
    detail::category_entry{"ERROR_TOO_MANY_SESS"},
    detail::category_entry{"ERROR_SHARING_PAUSED"},
    detail::category_entry{"ERROR_REQ_NOT_ACCEP"},
    detail::category_entry{"ERROR_REDIR_PAUSED"},
    detail::category_entry{"ERROR_FILE_EXISTS"},
    detail::category_entry{"ERROR_CANNOT_MAKE"},
    detail::category_entry{"ERROR_FAIL_I24"},
    detail::category_entry{"ERROR_OUT_OF_STRUCTURES"},
    detail::category_entry{"ERROR_ALREADY_ASSIGNED"},
    detail::category_entry{"ERROR_INVALID_PASSWORD"},
    detail::category_entry{"ERROR_INVALID_PARAMETER"},
    detail::category_entry{"ERROR_NET_WRITE_FAULT"},
    detail::category_entry{"ERROR_NO_PROC_SLOTS"},
    detail::category_entry{"ERROR_TOO_MANY_SEMAPHORES"},
    detail::category_entry{"ERROR_EXCL_SEM_ALREADY_OWNED"},
    detail::category_entry{"ERROR_SEM_IS_SET"},
    detail::category_entry{"ERROR_TOO_MANY_SEM_REQUESTS"},
    detail::category_entry{"ERROR_INVALID_AT_INTERRUPT_TIME"},
    detail::category_entry{"ERROR_SEM_OWNER_DIED"},
    detail::category_entry{"ERROR_SEM_USER_LIMIT"},
    detail::category_entry{"ERROR_DISK_CHANGE"},
    detail::category_entry{"ERROR_DRIVE_LOCKED"},
    detail::category_entry{"ERROR_BROKEN_PIPE"},
    detail::category_entry{"ERROR_OPEN_FAILED"},
    detail::category_entry{"ERROR_BUFFER_OVERFLOW"},
    detail::category_entry{"ERROR_DISK_FULL"},
    detail::category_entry{"ERROR_NO_MORE_SEARCH_HANDLES"},
    detail::category_entry{"ERROR_INVALID_TARGET_HANDLE"},
    detail::category_entry{"ERROR_INVALID_CATEGORY"},
    detail::category_entry{"ERROR_INVALID_VERIFY_SWITCH"},
    detail::category_entry{"ERROR_BAD_DRIVER_LEVEL"},
    detail::category_entry{"ERROR_CALL_NOT_IMPLEMENTED"},
    detail::category_entry{"ERROR_SEM_TIMEOUT"},
    detail::category_entry{"ERROR_INSUFFICIENT_BUFFER"},
    detail::category_entry{"ERROR_INVALID_NAME"},
    detail::category_entry{"ERROR_INVALID_LEVEL"},
    detail::category_entry{"ERROR_NO_VOLUME_LABEL"},
    detail::category_entry{"ERROR_MOD_NOT_FOUND"},
    detail::category_entry{"ERROR_PROC_NOT_FOUND"},
    detail::category_entry{"ERROR_WAIT_NO_CHILDREN"},
    detail::category_entry{"ERROR_CHILD_NOT_COMPLETE"},
    detail::category_entry{"ERROR_DIRECT_ACCESS_HANDLE"},
    detail::category_entry{"ERROR_NEGATIVE_SEEK"},
    detail::category_entry{"ERROR_SEEK_ON_DEVICE"},
    detail::category_entry{"ERROR_IS_JOIN_TARGET"},
    detail::category_entry{"ERROR_IS_JOINED"},
    detail::category_entry{"ERROR_IS_SUBSTED"},
    detail::category_entry{"ERROR_NOT_JOINED"},
    detail::category_entry{"ERROR_NOT_SUBSTED"},
    detail::category_entry{"ERROR_JOIN_TO_JOIN"},
    detail::category_entry{"ERROR_SUBST_TO_SUBST"},
    detail::category_entry{"ERROR_JOIN_TO_SUBST"},
    detail::category_entry{"ERROR_SUBST_TO_JOIN"},
    detail::category_entry{"ERROR_BUSY_DRIVE"},
    detail::category_entry{"ERROR_SAME_DRIVE"},
    detail::category_entry{"ERROR_DIR_NOT_ROOT"},
    detail::category_entry{"ERROR_DIR_NOT_EMPTY"},
    detail::category_entry{"ERROR_IS_SUBST_PATH"},
    detail::category_entry{"ERROR_IS_JOIN_PATH"},
    detail::category_entry{"ERROR_PATH_BUSY"},
    detail::category_entry{"ERROR_IS_SUBST_TARGET"},
    detail::category_entry{"ERROR_SYSTEM_TRACE"},
    detail::category_entry{"ERROR_INVALID_EVENT_COUNT"},
    detail::category_entry{"ERROR_TOO_MANY_MUXWAITERS"},
    detail::category_entry{"ERROR_INVALID_LIST_FORMAT"},
    detail::category_entry{"ERROR_LABEL_TOO_LONG"},
    detail::category_entry{"ERROR_TOO_MANY_TCBS"},
    detail::category_entry{"ERROR_SIGNAL_REFUSED"},
    detail::category_entry{"ERROR_DISCARDED"},
    detail::category_entry{"ERROR_NOT_LOCKED"},
    detail::category_entry{"ERROR_BAD_THREADID_ADDR"},
    detail::category_entry{"ERROR_BAD_ARGUMENTS"},
    detail::category_entry{"ERROR_BAD_PATHNAME"},
    detail::category_entry{"ERROR_SIGNAL_PENDING"},
    detail::category_entry{"ERROR_MAX_THRDS_REACHED"},
    detail::category_entry{"ERROR_LOCK_FAILED"},
    detail::category_entry{"ERROR_BUSY"},
    detail::category_entry{"ERROR_CANCEL_VIOLATION"},
    detail::category_entry{"ERROR_ATOMIC_LOCKS_NOT_SUPPORTED"},
    detail::category_entry{"ERROR_INVALID_SEGMENT_NUMBER"},
    detail::category_entry{"ERROR_INVALID_ORDINAL"},
    detail::category_entry{"ERROR_ALREADY_EXISTS"},
    detail::category_entry{"ERROR_INVALID_FLAG_NUMBER"},
    detail::category_entry{"ERROR_SEM_NOT_FOUND"},
    detail::category_entry{"ERROR_INVALID_STARTING_CODESEG"},
    detail::category_entry{"ERROR_INVALID_STACKSEG"},
    detail::category_entry{"ERROR_INVALID_MODULETYPE"},
    detail::category_entry{"ERROR_INVALID_EXE_SIGNATURE"},
    detail::category_entry{"ERROR_EXE_MARKED_INVALID"},
    detail::category_entry{"ERROR_BAD_EXE_FORMAT"},
    detail::category_entry{"ERROR_ITERATED_DATA_EXCEEDS_64k"},
    detail::category_entry{"ERROR_INVALID_MINALLOCSIZE"},
    detail::category_entry{"ERROR_DYNLINK_FROM_INVALID_RING"},
    detail::category_entry{"ERROR_IOPL_NOT_ENABLED"},
    detail::category_entry{"ERROR_INVALID_SEGDPL"},
    detail::category_entry{"ERROR_AUTODATASEG_EXCEEDS_64k"},
    detail::category_entry{"ERROR_RING2SEG_MUST_BE_MOVABLE"},
    detail::category_entry{"ERROR_RELOC_CHAIN_XEEDS_SEGLIM"},
    detail::category_entry{"ERROR_INFLOOP_IN_RELOC_CHAIN"},
    detail::category_entry{"ERROR_ENVVAR_NOT_FOUND"},
    detail::category_entry{"ERROR_NO_SIGNAL_SENT"},
    detail::category_entry{"ERROR_FILENAME_EXCED_RANGE"},
    detail::category_entry{"ERROR_RING2_STACK_IN_USE"},
    detail::category_entry{"ERROR_META_EXPANSION_TOO_LONG"},
    detail::category_entry{"ERROR_INVALID_SIGNAL_NUMBER"},
    detail::category_entry{"ERROR_THREAD_1_INACTIVE"},
    detail::category_entry{"ERROR_LOCKED"},
    detail::category_entry{"ERROR_TOO_MANY_MODULES"},
    detail::category_entry{"ERROR_NESTING_NOT_ALLOWED"},
    detail::category_entry{"ERROR_EXE_MACHINE_TYPE_MISMATCH"},
    detail::category_entry{"ERROR_BAD_PIPE"},
    detail::category_entry{"ERROR_PIPE_BUSY"},
    detail::category_entry{"ERROR_NO_DATA"},
    detail::category_entry{"ERROR_PIPE_NOT_CONNECTED"},
    detail::category_entry{"ERROR_MORE_DATA"},
    detail::category_entry{"ERROR_VC_DISCONNECTED"},
    detail::category_entry{"ERROR_INVALID_EA_NAME"},
    detail::category_entry{"ERROR_EA_LIST_INCONSISTENT"},
    detail::category_entry{"WAIT_TIMEOUT"},
    detail::category_entry{"ERROR_NO_MORE_ITEMS"},
    detail::category_entry{"ERROR_CANNOT_COPY"},
    detail::category_entry{"ERROR_DIRECTORY"},
    detail::category_entry{"ERROR_EAS_DIDNT_FIT"},
    detail::category_entry{"ERROR_EA_FILE_CORRUPT"},
    detail::category_entry{"ERROR_EA_TABLE_FULL"},
    detail::category_entry{"ERROR_INVALID_EA_HANDLE"},
    detail::category_entry{"ERROR_EAS_NOT_SUPPORTED"},
    detail::category_entry{"ERROR_NOT_OWNER"},
    detail::category_entry{"ERROR_TOO_MANY_POSTS"},
    detail::category_entry{"ERROR_PARTIAL_COPY"},
    detail::category_entry{"ERROR_OPLOCK_NOT_GRANTED"},
    detail::category_entry{"ERROR_INVALID_OPLOCK_PROTOCOL"},
    detail::category_entry{"ERROR_MR_MID_NOT_FOUND"},
    detail::category_entry{"ERROR_INVALID_ADDRESS"},
    detail::category_entry{"ERROR_ARITHMETIC_OVERFLOW"},
    detail::category_entry{"ERROR_PIPE_CONNECTED"},
    detail::category_entry{"ERROR_PIPE_LISTENING"},
    detail::category_entry{"ERROR_EA_ACCESS_DENIED"},
    detail::category_entry{"ERROR_OPERATION_ABORTED"},
    detail::category_entry{"ERROR_IO_INCOMPLETE"},
    detail::category_entry{"ERROR_IO_PENDING"},
    detail::category_entry{"ERROR_NOACCESS"},
    detail::category_entry{"ERROR_SWAPERROR"},
};

std::map<uint64_t, uint64_t> const win32_domain::category_table_ = {
    {0u, 0u},     {1u, 1u},     {2u, 2u},     {3u, 3u},     {4u, 4u},     {5u, 5u},
    {6u, 6u},     {7u, 7u},     {8u, 8u},     {9u, 9u},     {10u, 10u},   {11u, 11u},
    {12u, 12u},   {13u, 13u},   {14u, 14u},   {15u, 15u},   {16u, 16u},   {17u, 17u},
    {18u, 18u},   {19u, 19u},   {20u, 20u},   {21u, 21u},   {22u, 22u},   {23u, 23u},
    {24u, 24u},   {25u, 25u},   {26u, 26u},   {27u, 27u},   {28u, 28u},   {29u, 29u},
    {30u, 30u},   {31u, 31u},   {32u, 32u},   {33u, 33u},   {34u, 34u},   {36u, 35u},
    {38u, 36u},   {39u, 37u},   {50u, 38u},   {51u, 39u},   {52u, 40u},   {53u, 41u},
    {54u, 42u},   {55u, 43u},   {56u, 44u},   {57u, 45u},   {58u, 46u},   {59u, 47u},
    {60u, 48u},   {61u, 49u},   {62u, 50u},   {63u, 51u},   {64u, 52u},   {65u, 53u},
    {66u, 54u},   {67u, 55u},   {68u, 56u},   {69u, 57u},   {70u, 58u},   {71u, 59u},
    {72u, 60u},   {80u, 61u},   {82u, 62u},   {83u, 63u},   {84u, 64u},   {85u, 65u},
    {86u, 66u},   {87u, 67u},   {88u, 68u},   {89u, 69u},   {100u, 70u},  {101u, 71u},
    {102u, 72u},  {103u, 73u},  {104u, 74u},  {105u, 75u},  {106u, 76u},  {107u, 77u},
    {108u, 78u},  {109u, 79u},  {110u, 80u},  {111u, 81u},  {112u, 82u},  {113u, 83u},
    {114u, 84u},  {117u, 85u},  {118u, 86u},  {119u, 87u},  {120u, 88u},  {121u, 89u},
    {122u, 90u},  {123u, 91u},  {124u, 92u},  {125u, 93u},  {126u, 94u},  {127u, 95u},
    {128u, 96u},  {129u, 97u},  {130u, 98u},  {131u, 99u},  {132u, 100u}, {133u, 101u},
    {134u, 102u}, {135u, 103u}, {136u, 104u}, {137u, 105u}, {138u, 106u}, {139u, 107u},
    {140u, 108u}, {141u, 109u}, {142u, 110u}, {143u, 111u}, {144u, 112u}, {145u, 113u},
    {146u, 114u}, {147u, 115u}, {148u, 116u}, {149u, 117u}, {150u, 118u}, {151u, 119u},
    {152u, 120u}, {153u, 121u}, {154u, 122u}, {155u, 123u}, {156u, 124u}, {157u, 125u},
    {158u, 126u}, {159u, 127u}, {160u, 128u}, {161u, 129u}, {162u, 130u}, {164u, 131u},
    {167u, 132u}, {170u, 133u}, {173u, 134u}, {174u, 135u}, {180u, 136u}, {182u, 137u},
    {183u, 138u}, {186u, 139u}, {187u, 140u}, {188u, 141u}, {189u, 142u}, {190u, 143u},
    {191u, 144u}, {192u, 145u}, {193u, 146u}, {194u, 147u}, {195u, 148u}, {196u, 149u},
    {197u, 150u}, {198u, 151u}, {199u, 152u}, {200u, 153u}, {201u, 154u}, {202u, 155u},
    {203u, 156u}, {205u, 157u}, {206u, 158u}, {207u, 159u}, {208u, 160u}, {209u, 161u},
    {210u, 162u}, {212u, 163u}, {214u, 164u}, {215u, 165u}, {216u, 166u}, {230u, 167u},
    {231u, 168u}, {232u, 169u}, {233u, 170u}, {234u, 171u}, {240u, 172u}, {254u, 173u},
    {255u, 174u}, {258u, 175u}, {259u, 176u}, {266u, 177u}, {267u, 178u}, {275u, 179u},
    {276u, 180u}, {277u, 181u}, {278u, 182u}, {282u, 183u}, {288u, 184u}, {298u, 185u},
    {299u, 186u}, {300u, 187u}, {301u, 188u}, {317u, 189u}, {487u, 190u}, {534u, 191u},
    {535u, 192u}, {536u, 193u}, {994u, 194u}, {995u, 195u}, {996u, 196u}, {997u, 197u},
    {998u, 198u}, {999u, 199u},
};

}  // namespace ctl
