#include "wall.hpp"

namespace ctl {

wall enclosure::create(wall_code const& code) {
  return {this, code.kind, code.inst};
}

enclosure::wall_code enclosure::reveal(wall const& wall) {
  return {wall.kind_, wall.instance_};
}

std::array<kind_entry, 125> posix_enclosure::kinds_ = {
    kind_entry{},
    kind_entry{"Operation not permitted"},
    kind_entry{"No such file or directory"},
    kind_entry{"No such process"},
    kind_entry{"Interrupted system call"},
    kind_entry{"I/O error"},
    kind_entry{"No such device or address"},
    kind_entry{"Arg list too long"},
    kind_entry{"Exec format error"},
    kind_entry{"Bad file number"},
    kind_entry{"No child processes"},
    kind_entry{"Try again"},
    kind_entry{"Out of memory"},
    kind_entry{"Permission denied"},
    kind_entry{"Bad address"},
    kind_entry{"Block device required"},
    kind_entry{"Device or resource busy"},
    kind_entry{"File exists"},
    kind_entry{"Cross-device link"},
    kind_entry{"No such device"},
    kind_entry{"Not a directory"},
    kind_entry{"Is a directory"},
    kind_entry{"Invalid argument"},
    kind_entry{"File table overflow"},
    kind_entry{"Too many open files"},
    kind_entry{"Not a typewriter"},
    kind_entry{"Text file busy"},
    kind_entry{"File too large"},
    kind_entry{"No space left on device"},
    kind_entry{"Illegal seek"},
    kind_entry{"Read-only file system"},
    kind_entry{"Too many links"},
    kind_entry{"Broken pipe"},
    kind_entry{"Math argument out of domain of func"},
    kind_entry{"Math result not representable"},
    kind_entry{"Resource deadlock would occur"},
    kind_entry{"File name too long"},
    kind_entry{"No record locks available"},
    kind_entry{"Function not implemented"},
    kind_entry{"Directory not empty"},
    kind_entry{"Too many symbolic links encountered"},
    kind_entry{"Try again"},
    kind_entry{"No message of desired type"},
    kind_entry{"Identifier removed"},
    kind_entry{"Channel number out of range"},
    kind_entry{"Level 2 not synchronized"},
    kind_entry{"Level 3 halted"},
    kind_entry{"Level 3 reset"},
    kind_entry{"Link number out of range"},
    kind_entry{"Protocol driver not attached"},
    kind_entry{"No CSI structure available"},
    kind_entry{"Level 2 halted"},
    kind_entry{"Invalid exchange"},
    kind_entry{"Invalid request descriptor"},
    kind_entry{"Exchange full"},
    kind_entry{"No anode"},
    kind_entry{"Invalid request code"},
    kind_entry{"Invalid slot"},
    kind_entry{"Resource deadlock would occur"},
    kind_entry{"Bad font file format"},
    kind_entry{"Device not a stream"},
    kind_entry{"No data available"},
    kind_entry{"Timer expired"},
    kind_entry{"Out of streams resources"},
    kind_entry{"Machine is not on the network"},
    kind_entry{"Package not installed"},
    kind_entry{"Object is remote"},
    kind_entry{"Link has been severed"},
    kind_entry{"Advertise error"},
    kind_entry{"Srmount error"},
    kind_entry{"Communication error on send"},
    kind_entry{"Protocol error"},
    kind_entry{"Multihop attempted"},
    kind_entry{"RFS specific error"},
    kind_entry{"Not a data message"},
    kind_entry{"Value too large for defined data type"},
    kind_entry{"Name not unique on network"},
    kind_entry{"File descriptor in bad state"},
    kind_entry{"Remote address changed"},
    kind_entry{"Can not access a needed shared library"},
    kind_entry{"Accessing a corrupted shared library"},
    kind_entry{".lib section in a.out corrupted"},
    kind_entry{"Attempting to link in too many shared libraries"},
    kind_entry{"Cannot exec a shared library directly"},
    kind_entry{"Illegal byte sequence"},
    kind_entry{"Interrupted system call should be restarted"},
    kind_entry{"Streams pipe error"},
    kind_entry{"Too many users"},
    kind_entry{"Socket operation on non-socket"},
    kind_entry{"Destination address required"},
    kind_entry{"Message too long"},
    kind_entry{"Protocol wrong type for socket"},
    kind_entry{"Protocol not available"},
    kind_entry{"Protocol not supported"},
    kind_entry{"Socket type not supported"},
    kind_entry{"Operation not supported on transport endpoint"},
    kind_entry{"Protocol family not supported"},
    kind_entry{"Address family not supported by protocol"},
    kind_entry{"Address already in use"},
    kind_entry{"Cannot assign requested address"},
    kind_entry{"Network is down"},
    kind_entry{"Network is unreachable"},
    kind_entry{"Network dropped connection because of reset"},
    kind_entry{"Software caused connection abort"},
    kind_entry{"Connection reset by peer"},
    kind_entry{"No buffer space available"},
    kind_entry{"Transport endpoint is already connected"},
    kind_entry{"Transport endpoint is not connected"},
    kind_entry{"Cannot send after transport endpoint shutdown"},
    kind_entry{"Too many references: cannot splice"},
    kind_entry{"Connection timed out"},
    kind_entry{"Connection refused"},
    kind_entry{"Host is down"},
    kind_entry{"No route to host"},
    kind_entry{"Operation already in progress"},
    kind_entry{"Operation now in progress"},
    kind_entry{"Stale NFS file handle"},
    kind_entry{"Structure needs cleaning"},
    kind_entry{"Not a XENIX named type file"},
    kind_entry{"No XENIX semaphores available"},
    kind_entry{"Is a named type file"},
    kind_entry{"Remote I/O error"},
    kind_entry{"Quota exceeded"},
    kind_entry{"No medium found"},
    kind_entry{"Wrong medium type "},
};
}  // namespace ctl
