#include "wall.hpp"

namespace ctl {

wall enclosure::create(code code) { return {this, code}; }
code enclosure::reveal(wall wall) { return wall.code_; }

std::array<kind_entry, 125> const posix_enclosure::kinds_ = {
    kind_entry{},
    kind_entry{"Operation not permitted"},
    kind_entry{"No such file or directory"},
    kind_entry{"No such process"},
    kind_entry{"Interrupted system call"},
    kind_entry{"I/O error"},
    kind_entry{"No such device or address"},
    kind_entry{"Arg list too long"},
    kind_entry{"Exec format error"},
    kind_entry{"Bad file number"},
    kind_entry{"No child processes"},
    kind_entry{"Try again"},
    kind_entry{"Out of memory"},
    kind_entry{"Permission denied"},
    kind_entry{"Bad address"},
    kind_entry{"Block device required"},
    kind_entry{"Device or resource busy"},
    kind_entry{"File exists"},
    kind_entry{"Cross-device link"},
    kind_entry{"No such device"},
    kind_entry{"Not a directory"},
    kind_entry{"Is a directory"},
    kind_entry{"Invalid argument"},
    kind_entry{"File table overflow"},
    kind_entry{"Too many open files"},
    kind_entry{"Not a typewriter"},
    kind_entry{"Text file busy"},
    kind_entry{"File too large"},
    kind_entry{"No space left on device"},
    kind_entry{"Illegal seek"},
    kind_entry{"Read-only file system"},
    kind_entry{"Too many links"},
    kind_entry{"Broken pipe"},
    kind_entry{"Math argument out of domain of func"},
    kind_entry{"Math result not representable"},
    kind_entry{"Resource deadlock would occur"},
    kind_entry{"File name too long"},
    kind_entry{"No record locks available"},
    kind_entry{"Function not implemented"},
    kind_entry{"Directory not empty"},
    kind_entry{"Too many symbolic links encountered"},
    kind_entry{"Try again"},
    kind_entry{"No message of desired type"},
    kind_entry{"Identifier removed"},
    kind_entry{"Channel number out of range"},
    kind_entry{"Level 2 not synchronized"},
    kind_entry{"Level 3 halted"},
    kind_entry{"Level 3 reset"},
    kind_entry{"Link number out of range"},
    kind_entry{"Protocol driver not attached"},
    kind_entry{"No CSI structure available"},
    kind_entry{"Level 2 halted"},
    kind_entry{"Invalid exchange"},
    kind_entry{"Invalid request descriptor"},
    kind_entry{"Exchange full"},
    kind_entry{"No anode"},
    kind_entry{"Invalid request code"},
    kind_entry{"Invalid slot"},
    kind_entry{"Resource deadlock would occur"},
    kind_entry{"Bad font file format"},
    kind_entry{"Device not a stream"},
    kind_entry{"No data available"},
    kind_entry{"Timer expired"},
    kind_entry{"Out of streams resources"},
    kind_entry{"Machine is not on the network"},
    kind_entry{"Package not installed"},
    kind_entry{"Object is remote"},
    kind_entry{"Link has been severed"},
    kind_entry{"Advertise error"},
    kind_entry{"Srmount error"},
    kind_entry{"Communication error on send"},
    kind_entry{"Protocol error"},
    kind_entry{"Multihop attempted"},
    kind_entry{"RFS specific error"},
    kind_entry{"Not a data message"},
    kind_entry{"Value too large for defined data type"},
    kind_entry{"Name not unique on network"},
    kind_entry{"File descriptor in bad state"},
    kind_entry{"Remote address changed"},
    kind_entry{"Can not access a needed shared library"},
    kind_entry{"Accessing a corrupted shared library"},
    kind_entry{".lib section in a.out corrupted"},
    kind_entry{"Attempting to link in too many shared libraries"},
    kind_entry{"Cannot exec a shared library directly"},
    kind_entry{"Illegal byte sequence"},
    kind_entry{"Interrupted system call should be restarted"},
    kind_entry{"Streams pipe error"},
    kind_entry{"Too many users"},
    kind_entry{"Socket operation on non-socket"},
    kind_entry{"Destination address required"},
    kind_entry{"Message too long"},
    kind_entry{"Protocol wrong type for socket"},
    kind_entry{"Protocol not available"},
    kind_entry{"Protocol not supported"},
    kind_entry{"Socket type not supported"},
    kind_entry{"Operation not supported on transport endpoint"},
    kind_entry{"Protocol family not supported"},
    kind_entry{"Address family not supported by protocol"},
    kind_entry{"Address already in use"},
    kind_entry{"Cannot assign requested address"},
    kind_entry{"Network is down"},
    kind_entry{"Network is unreachable"},
    kind_entry{"Network dropped connection because of reset"},
    kind_entry{"Software caused connection abort"},
    kind_entry{"Connection reset by peer"},
    kind_entry{"No buffer space available"},
    kind_entry{"Transport endpoint is already connected"},
    kind_entry{"Transport endpoint is not connected"},
    kind_entry{"Cannot send after transport endpoint shutdown"},
    kind_entry{"Too many references: cannot splice"},
    kind_entry{"Connection timed out"},
    kind_entry{"Connection refused"},
    kind_entry{"Host is down"},
    kind_entry{"No route to host"},
    kind_entry{"Operation already in progress"},
    kind_entry{"Operation now in progress"},
    kind_entry{"Stale NFS file handle"},
    kind_entry{"Structure needs cleaning"},
    kind_entry{"Not a XENIX named type file"},
    kind_entry{"No XENIX semaphores available"},
    kind_entry{"Is a named type file"},
    kind_entry{"Remote I/O error"},
    kind_entry{"Quota exceeded"},
    kind_entry{"No medium found"},
    kind_entry{"Wrong medium type "},
};

std::map<int, kind_entry> const win32_enclosure::kinds_ = {
    {0, kind_entry{"ERROR_SUCCESS"}},
    {1, kind_entry{"ERROR_INVALID_FUNCTION"}},
    {2, kind_entry{"ERROR_FILE_NOT_FOUND"}},
    {3, kind_entry{"ERROR_PATH_NOT_FOUND"}},
    {4, kind_entry{"ERROR_TOO_MANY_OPEN_FILES"}},
    {5, kind_entry{"ERROR_ACCESS_DENIED"}},
    {6, kind_entry{"ERROR_INVALID_HANDLE"}},
    {7, kind_entry{"ERROR_ARENA_TRASHED"}},
    {8, kind_entry{"ERROR_NOT_ENOUGH_MEMORY"}},
    {9, kind_entry{"ERROR_INVALID_BLOCK"}},
    {10, kind_entry{"ERROR_BAD_ENVIRONMENT"}},
    {11, kind_entry{"ERROR_BAD_FORMAT"}},
    {12, kind_entry{"ERROR_INVALID_ACCESS"}},
    {13, kind_entry{"ERROR_INVALID_DATA"}},
    {14, kind_entry{"ERROR_OUTOFMEMORY"}},
    {15, kind_entry{"ERROR_INVALID_DRIVE"}},
    {16, kind_entry{"ERROR_CURRENT_DIRECTORY"}},
    {17, kind_entry{"ERROR_NOT_SAME_DEVICE"}},
    {18, kind_entry{"ERROR_NO_MORE_FILES"}},
    {19, kind_entry{"ERROR_WRITE_PROTECT"}},
    {20, kind_entry{"ERROR_BAD_UNIT"}},
    {21, kind_entry{"ERROR_NOT_READY"}},
    {22, kind_entry{"ERROR_BAD_COMMAND"}},
    {23, kind_entry{"ERROR_CRC"}},
    {24, kind_entry{"ERROR_BAD_LENGTH"}},
    {25, kind_entry{"ERROR_SEEK"}},
    {26, kind_entry{"ERROR_NOT_DOS_DISK"}},
    {27, kind_entry{"ERROR_SECTOR_NOT_FOUND"}},
    {28, kind_entry{"ERROR_OUT_OF_PAPER"}},
    {29, kind_entry{"ERROR_WRITE_FAULT"}},
    {30, kind_entry{"ERROR_READ_FAULT"}},
    {31, kind_entry{"ERROR_GEN_FAILURE"}},
    {32, kind_entry{"ERROR_SHARING_VIOLATION"}},
    {33, kind_entry{"ERROR_LOCK_VIOLATION"}},
    {34, kind_entry{"ERROR_WRONG_DISK"}},
    {36, kind_entry{"ERROR_SHARING_BUFFER_EXCEEDED"}},
    {38, kind_entry{"ERROR_HANDLE_EOF"}},
    {39, kind_entry{"ERROR_HANDLE_DISK_FULL"}},
    {50, kind_entry{"ERROR_NOT_SUPPORTED"}},
    {51, kind_entry{"ERROR_REM_NOT_LIST"}},
    {52, kind_entry{"ERROR_DUP_NAME"}},
    {53, kind_entry{"ERROR_BAD_NETPATH"}},
    {54, kind_entry{"ERROR_NETWORK_BUSY"}},
    {55, kind_entry{"ERROR_DEV_NOT_EXIST"}},
    {56, kind_entry{"ERROR_TOO_MANY_CMDS"}},
    {57, kind_entry{"ERROR_ADAP_HDW_ERR"}},
    {58, kind_entry{"ERROR_BAD_NET_RESP"}},
    {59, kind_entry{"ERROR_UNEXP_NET_ERR"}},
    {60, kind_entry{"ERROR_BAD_REM_ADAP"}},
    {61, kind_entry{"ERROR_PRINTQ_FULL"}},
    {62, kind_entry{"ERROR_NO_SPOOL_SPACE"}},
    {63, kind_entry{"ERROR_PRINT_CANCELED"}},
    {64, kind_entry{"ERROR_NETNAME_DELETED"}},
    {65, kind_entry{"ERROR_NETWORK_ACCESS_DENIED"}},
    {66, kind_entry{"ERROR_BAD_DEV_TYPE"}},
    {67, kind_entry{"ERROR_BAD_NET_NAME"}},
    {68, kind_entry{"ERROR_TOO_MANY_NAMES"}},
    {69, kind_entry{"ERROR_TOO_MANY_SESS"}},
    {70, kind_entry{"ERROR_SHARING_PAUSED"}},
    {71, kind_entry{"ERROR_REQ_NOT_ACCEP"}},
    {72, kind_entry{"ERROR_REDIR_PAUSED"}},
    {80, kind_entry{"ERROR_FILE_EXISTS"}},
    {82, kind_entry{"ERROR_CANNOT_MAKE"}},
    {83, kind_entry{"ERROR_FAIL_I24"}},
    {84, kind_entry{"ERROR_OUT_OF_STRUCTURES"}},
    {85, kind_entry{"ERROR_ALREADY_ASSIGNED"}},
    {86, kind_entry{"ERROR_INVALID_PASSWORD"}},
    {87, kind_entry{"ERROR_INVALID_PARAMETER"}},
    {88, kind_entry{"ERROR_NET_WRITE_FAULT"}},
    {89, kind_entry{"ERROR_NO_PROC_SLOTS"}},
    {100, kind_entry{"ERROR_TOO_MANY_SEMAPHORES"}},
    {101, kind_entry{"ERROR_EXCL_SEM_ALREADY_OWNED"}},
    {102, kind_entry{"ERROR_SEM_IS_SET"}},
    {103, kind_entry{"ERROR_TOO_MANY_SEM_REQUESTS"}},
    {104, kind_entry{"ERROR_INVALID_AT_INTERRUPT_TIME"}},
    {105, kind_entry{"ERROR_SEM_OWNER_DIED"}},
    {106, kind_entry{"ERROR_SEM_USER_LIMIT"}},
    {107, kind_entry{"ERROR_DISK_CHANGE"}},
    {108, kind_entry{"ERROR_DRIVE_LOCKED"}},
    {109, kind_entry{"ERROR_BROKEN_PIPE"}},
    {110, kind_entry{"ERROR_OPEN_FAILED"}},
    {111, kind_entry{"ERROR_BUFFER_OVERFLOW"}},
    {112, kind_entry{"ERROR_DISK_FULL"}},
    {113, kind_entry{"ERROR_NO_MORE_SEARCH_HANDLES"}},
    {114, kind_entry{"ERROR_INVALID_TARGET_HANDLE"}},
    {117, kind_entry{"ERROR_INVALID_CATEGORY"}},
    {118, kind_entry{"ERROR_INVALID_VERIFY_SWITCH"}},
    {119, kind_entry{"ERROR_BAD_DRIVER_LEVEL"}},
    {120, kind_entry{"ERROR_CALL_NOT_IMPLEMENTED"}},
    {121, kind_entry{"ERROR_SEM_TIMEOUT"}},
    {122, kind_entry{"ERROR_INSUFFICIENT_BUFFER"}},
    {123, kind_entry{"ERROR_INVALID_NAME"}},
    {124, kind_entry{"ERROR_INVALID_LEVEL"}},
    {125, kind_entry{"ERROR_NO_VOLUME_LABEL"}},
    {126, kind_entry{"ERROR_MOD_NOT_FOUND"}},
    {127, kind_entry{"ERROR_PROC_NOT_FOUND"}},
    {128, kind_entry{"ERROR_WAIT_NO_CHILDREN"}},
    {129, kind_entry{"ERROR_CHILD_NOT_COMPLETE"}},
    {130, kind_entry{"ERROR_DIRECT_ACCESS_HANDLE"}},
    {131, kind_entry{"ERROR_NEGATIVE_SEEK"}},
    {132, kind_entry{"ERROR_SEEK_ON_DEVICE"}},
    {133, kind_entry{"ERROR_IS_JOIN_TARGET"}},
    {134, kind_entry{"ERROR_IS_JOINED"}},
    {135, kind_entry{"ERROR_IS_SUBSTED"}},
    {136, kind_entry{"ERROR_NOT_JOINED"}},
    {137, kind_entry{"ERROR_NOT_SUBSTED"}},
    {138, kind_entry{"ERROR_JOIN_TO_JOIN"}},
    {139, kind_entry{"ERROR_SUBST_TO_SUBST"}},
    {140, kind_entry{"ERROR_JOIN_TO_SUBST"}},
    {141, kind_entry{"ERROR_SUBST_TO_JOIN"}},
    {142, kind_entry{"ERROR_BUSY_DRIVE"}},
    {143, kind_entry{"ERROR_SAME_DRIVE"}},
    {144, kind_entry{"ERROR_DIR_NOT_ROOT"}},
    {145, kind_entry{"ERROR_DIR_NOT_EMPTY"}},
    {146, kind_entry{"ERROR_IS_SUBST_PATH"}},
    {147, kind_entry{"ERROR_IS_JOIN_PATH"}},
    {148, kind_entry{"ERROR_PATH_BUSY"}},
    {149, kind_entry{"ERROR_IS_SUBST_TARGET"}},
    {150, kind_entry{"ERROR_SYSTEM_TRACE"}},
    {151, kind_entry{"ERROR_INVALID_EVENT_COUNT"}},
    {152, kind_entry{"ERROR_TOO_MANY_MUXWAITERS"}},
    {153, kind_entry{"ERROR_INVALID_LIST_FORMAT"}},
    {154, kind_entry{"ERROR_LABEL_TOO_LONG"}},
    {155, kind_entry{"ERROR_TOO_MANY_TCBS"}},
    {156, kind_entry{"ERROR_SIGNAL_REFUSED"}},
    {157, kind_entry{"ERROR_DISCARDED"}},
    {158, kind_entry{"ERROR_NOT_LOCKED"}},
    {159, kind_entry{"ERROR_BAD_THREADID_ADDR"}},
    {160, kind_entry{"ERROR_BAD_ARGUMENTS"}},
    {161, kind_entry{"ERROR_BAD_PATHNAME"}},
    {162, kind_entry{"ERROR_SIGNAL_PENDING"}},
    {164, kind_entry{"ERROR_MAX_THRDS_REACHED"}},
    {167, kind_entry{"ERROR_LOCK_FAILED"}},
    {170, kind_entry{"ERROR_BUSY"}},
    {173, kind_entry{"ERROR_CANCEL_VIOLATION"}},
    {174, kind_entry{"ERROR_ATOMIC_LOCKS_NOT_SUPPORTED"}},
    {180, kind_entry{"ERROR_INVALID_SEGMENT_NUMBER"}},
    {182, kind_entry{"ERROR_INVALID_ORDINAL"}},
    {183, kind_entry{"ERROR_ALREADY_EXISTS"}},
    {186, kind_entry{"ERROR_INVALID_FLAG_NUMBER"}},
    {187, kind_entry{"ERROR_SEM_NOT_FOUND"}},
    {188, kind_entry{"ERROR_INVALID_STARTING_CODESEG"}},
    {189, kind_entry{"ERROR_INVALID_STACKSEG"}},
    {190, kind_entry{"ERROR_INVALID_MODULETYPE"}},
    {191, kind_entry{"ERROR_INVALID_EXE_SIGNATURE"}},
    {192, kind_entry{"ERROR_EXE_MARKED_INVALID"}},
    {193, kind_entry{"ERROR_BAD_EXE_FORMAT"}},
    {194, kind_entry{"ERROR_ITERATED_DATA_EXCEEDS_64k"}},
    {195, kind_entry{"ERROR_INVALID_MINALLOCSIZE"}},
    {196, kind_entry{"ERROR_DYNLINK_FROM_INVALID_RING"}},
    {197, kind_entry{"ERROR_IOPL_NOT_ENABLED"}},
    {198, kind_entry{"ERROR_INVALID_SEGDPL"}},
    {199, kind_entry{"ERROR_AUTODATASEG_EXCEEDS_64k"}},
    {200, kind_entry{"ERROR_RING2SEG_MUST_BE_MOVABLE"}},
    {201, kind_entry{"ERROR_RELOC_CHAIN_XEEDS_SEGLIM"}},
    {202, kind_entry{"ERROR_INFLOOP_IN_RELOC_CHAIN"}},
    {203, kind_entry{"ERROR_ENVVAR_NOT_FOUND"}},
    {205, kind_entry{"ERROR_NO_SIGNAL_SENT"}},
    {206, kind_entry{"ERROR_FILENAME_EXCED_RANGE"}},
    {207, kind_entry{"ERROR_RING2_STACK_IN_USE"}},
    {208, kind_entry{"ERROR_META_EXPANSION_TOO_LONG"}},
    {209, kind_entry{"ERROR_INVALID_SIGNAL_NUMBER"}},
    {210, kind_entry{"ERROR_THREAD_1_INACTIVE"}},
    {212, kind_entry{"ERROR_LOCKED"}},
    {214, kind_entry{"ERROR_TOO_MANY_MODULES"}},
    {215, kind_entry{"ERROR_NESTING_NOT_ALLOWED"}},
    {216, kind_entry{"ERROR_EXE_MACHINE_TYPE_MISMATCH"}},
    {230, kind_entry{"ERROR_BAD_PIPE"}},
    {231, kind_entry{"ERROR_PIPE_BUSY"}},
    {232, kind_entry{"ERROR_NO_DATA"}},
    {233, kind_entry{"ERROR_PIPE_NOT_CONNECTED"}},
    {234, kind_entry{"ERROR_MORE_DATA"}},
    {240, kind_entry{"ERROR_VC_DISCONNECTED"}},
    {254, kind_entry{"ERROR_INVALID_EA_NAME"}},
    {255, kind_entry{"ERROR_EA_LIST_INCONSISTENT"}},
    {258, kind_entry{"WAIT_TIMEOUT"}},
    {259, kind_entry{"ERROR_NO_MORE_ITEMS"}},
    {266, kind_entry{"ERROR_CANNOT_COPY"}},
    {267, kind_entry{"ERROR_DIRECTORY"}},
    {275, kind_entry{"ERROR_EAS_DIDNT_FIT"}},
    {276, kind_entry{"ERROR_EA_FILE_CORRUPT"}},
    {277, kind_entry{"ERROR_EA_TABLE_FULL"}},
    {278, kind_entry{"ERROR_INVALID_EA_HANDLE"}},
    {282, kind_entry{"ERROR_EAS_NOT_SUPPORTED"}},
    {288, kind_entry{"ERROR_NOT_OWNER"}},
    {298, kind_entry{"ERROR_TOO_MANY_POSTS"}},
    {299, kind_entry{"ERROR_PARTIAL_COPY"}},
    {300, kind_entry{"ERROR_OPLOCK_NOT_GRANTED"}},
    {301, kind_entry{"ERROR_INVALID_OPLOCK_PROTOCOL"}},
    {317, kind_entry{"ERROR_MR_MID_NOT_FOUND"}},
    {487, kind_entry{"ERROR_INVALID_ADDRESS"}},
    {534, kind_entry{"ERROR_ARITHMETIC_OVERFLOW"}},
    {535, kind_entry{"ERROR_PIPE_CONNECTED"}},
    {536, kind_entry{"ERROR_PIPE_LISTENING"}},
    {994, kind_entry{"ERROR_EA_ACCESS_DENIED"}},
    {995, kind_entry{"ERROR_OPERATION_ABORTED"}},
    {996, kind_entry{"ERROR_IO_INCOMPLETE"}},
    {997, kind_entry{"ERROR_IO_PENDING"}},
    {998, kind_entry{"ERROR_NOACCESS"}},
    {999, kind_entry{"ERROR_SWAPERROR"}},
};

}  // namespace ctl
