#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_cxx')
    ctx.add_option('--build', action='store', default='', help='configuration to build')

def configure(ctx):
    ctx.load('compiler_cxx')
    ctx.env.variant = ctx.options.build
    default = ctx.env

    ctx.setenv('debug', default)
    ctx.env.append_unique('CXXFLAGS', ['-g', '-std=c++11'])

    ctx.setenv('release', default)
    ctx.env.append_unique('CXXFLAGS', ['-g', '-O2', '-std=c++11'])

    ctx.setenv('shipping', default)
    ctx.env.append_unique('CXXFLAGS', ['-O2', '-std=c++11'])


def build(ctx):
    variant = ctx.variant if len(ctx.variant) > 0 else ctx.env.variant
    print 'Using build type: {}'.format(variant)

    ctx.env = ctx.all_envs[variant]
    ctx.program(source='main.cpp', target='game', includes='.')

# Create a custom builder for each combination of context and configuration 
from waflib.Build import BuildContext, CleanContext, InstallContext, UninstallContext
for configuration in ['debug', 'release', 'shipping']:
    for context in (BuildContext, CleanContext, InstallContext, UninstallContext):
        class Builder(context):
            cmd =  configuration + '_' + context.__name__.replace('Context','').lower()
            variant = configuration
