#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')
    conf.env.append_unique('CXXFLAGS', ['-g', '-std=c++11'])

def build(bld):
	bld.program(source='main.cpp', target='game', includes='.')

